/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const ArrowDropUpIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function ArrowDropUpIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0z" fill="none" />
        <path d="m7 14 5-5 5 5z" />
      </SVGIcon>
    );
  }
);
