# core
app-bar:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/app-bar/**/*

autocomplete:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/autocomplete/**/*

avatar:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/avatar/**/*

badge:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/badge/**/*

box:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/box/**/*

button:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/button/**/*

card:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/card/**/*

chip:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/chip/**/*

datetime:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/datetime/**/*

dialog:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/dialog/**/*

divider:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/divider/**/*

expansion-panel:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/expansion-panel/**/*

file-input:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/files/**/*

form:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/form/**/*

icon:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/icon/**/*

interaction:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/interaction/**/*

layout:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/layout/**/*

link:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/link/**/*

list:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/list/**/*

media-queries:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/media-queries/**/*

menu:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/menu/**/*

navigation:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/navigation/**/*

overlay:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/overlay/**/*

portal:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/portal/**/*

progress:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/progress/**/*

responsive-item:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/responsive-item/**/*

segmented-button:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/segmented-button/**/*

sheet:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/sheet/**/*

snackbar:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/snackbar/**/*

spinbutton:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/spinbutton/**/*

table:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/table/**/*

tabs:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/tabs/**/*

test-utils:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/test-utils/**/*

theme:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/theme/**/*

tooltip:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/tooltip/**/*

transition:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/transition/**/*

tree:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/tree/**/*

typography:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/typography/**/*

window-splitter:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/window-splitter/**/*

styles:
  - changed-files:
      - any-glob-to-any-file:
          - packages/**/*.scss

utils:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/src/draggable/**/*
          - packages/core/src/error-boundary/**/*
          - packages/core/src/focus/**/*
          - packages/core/src/hoverMode/**/*
          - packages/core/src/movement/**/*
          - packages/core/src/positioning/**/*
          - packages/core/src/scroll/**/*
          - packages/core/src/searching/**/*
          - packages/core/src/storage/**/*
          - packages/core/src/suspense/**/*
          - packages/core/src/utils/**/*
          - packages/core/src/*.ts
          - packages/core/src/*.tsx

# other packages
code:
  - changed-files:
      - any-glob-to-any-file:
          - packages/code/**/*

codemod:
  - changed-files:
      - any-glob-to-any-file:
          - packages/codemod/**/*

material-icons:
  - changed-files:
      - any-glob-to-any-file:
          - packages/material-icons/**/*

vite-material-symbols-plugin:
  - changed-files:
      - any-glob-to-any-file:
          - packages/vite-material-symbols-plugin/**/*

# internal stuffs
docs:
  - changed-files:
      - any-glob-to-any-file:
          - apps/docs/**/*
          - docs/**/*

examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**/*

playground:
  - changed-files:
      - any-glob-to-any-file:
          - apps/next-playground/**/*
          - apps/vite-playground/**/*
