parser: 'babel-eslint'
extends: 'airbnb'
env:
  browser: true
  node: true
rules:
  arrow-parens: 0
  no-param-reassign: 0
  no-console: 0
  max-len: 0
  object-curly-newline: 0
  function-paren-newline: 0
  no-underscore-dangle: 0
  no-shadow: 0
  class-methods-use-this: 0
  new-cap: 0
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never


  no-mixed-operators: 0

  global-require: 0
  import/extensions: 0
  import/no-dynamic-require: 0
  import/imports-first: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/newline-after-import: 0

  react/no-unused-prop-types: 1
  react/forbid-prop-types: 1
  react/prefer-stateless-function: 1
  react/no-find-dom-node: 1
