export const FETCH_REQUEST = Symbol('FETCH_REQUEST');
export const FETCH_SUCCESS = Symbol('FETCH_SUCCESS');
export const FETCH_FAILURE = Symbol('FETCH_FAILURE');
export const FETCH_DOCGEN_REQUEST = Symbol('FETCH_DOCGEN_REQUEST');
export const FETCH_DOCGEN_SUCCESS = Symbol('FETCH_DOCGEN_SUCCESS');
export const FETCH_DOCGEN_FAILURE = Symbol('FETCH_DOCGEN_FAILURE');
export const FETCH_SASSDOC_REQUEST = Symbol('FETCH_SASSDOC_REQUEST');
export const FETCH_SASSDOC_SUCCESS = Symbol('FETCH_SASSDOC_SUCCESS');
export const FETCH_SASSDOC_FAILURE = Symbol('FETCH_SASSDOC_FAILURE');

export const ADD_NOTIFICATION = Symbol('ADD_NOTIFICATION');
export const DISMISS_NOTIFICATION = Symbol('DISMISS_NOTIFICATION');
