printWidth: 80
trailingComma: es5

plugins:
  - "@trivago/prettier-plugin-sort-imports"

importOrder:
  - "<THIRD_PARTY_MODULES>"
  - "^[@.]/rmdConfig.js$"
  - "^[@.]/constants/rmdConfig.js$"
  - "^@/(.*)$"
  - "^[./]"
importOrderSeparation: true
importOrderSortSpecifiers: true
