/** this is an auto-generated file from @react-md/dev-utils */
export default {
  "rmd-dialog-elevation": 16,
  "rmd-dialog-z-index": 30,
  "rmd-dialog-vertical-margin": "1.5rem",
  "rmd-dialog-horizontal-margin": "2.5rem",
  "rmd-dialog-header-padding": "1.5rem",
  "rmd-dialog-header-padding-bottom": "1.25rem",
  "rmd-dialog-content-padding": "1.5rem",
  "rmd-dialog-footer-padding": "0.5rem",
  "rmd-dialog-transition-distance": "1.875rem",
  "rmd-dialog-enter-duration": "0.2s",
  "rmd-dialog-leave-duration": "0.15s",
  "rmd-dialog-min-width": "17.5rem",
  "rmd-dialog-theme-values": {
    "horizontal-margin": "2.5rem",
    "vertical-margin": "1.5rem",
    "min-width": "17.5rem",
    "header-padding": "1.5rem",
    "header-padding-bottom": "1.25rem",
    "content-padding": "1.5rem",
    "footer-padding": "0.5rem",
    "z-index": 30,
  },
};
