/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const BrandingWatermarkIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function BrandingWatermarkIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0V0z" fill="none" />
        <path d="M23 3H1v18h22V3zm-2 16h-9v-6h9v6z" />
      </SVGIcon>
    );
  }
);
