printWidth: 80
trailingComma: es5

plugins:
  - "@trivago/prettier-plugin-sort-imports"

importOrder:
  - "<THIRD_PARTY_MODULES>"
  - "^./index.scss"
  - "^@/(.*)$"
  - "^[./]"
importOrderSeparation: true
importOrderSortSpecifiers: true
