/** this is an auto-generated file from @react-md/dev-utils */
export default {
  "rmd-states-use-ripple": true,
  "rmd-states-prevent-color-pollution": true,
  "rmd-states-light-theme-background-color": "#000",
  "rmd-states-dark-theme-background-color": "#fff",
  "rmd-states-light-theme-ripple-background-color": "rgba(0, 0, 0, 0.08)",
  "rmd-states-dark-theme-ripple-background-color": "rgba(255, 255, 255, 0.08)",
  "rmd-states-background-color": "#000",
  "rmd-states-ripple-background-color": "rgba(0, 0, 0, 0.08)",
  "rmd-states-ripple-opacity": 1,
  "rmd-states-hover-opacity": 0.08,
  "rmd-states-focus-opacity": 0.24,
  "rmd-states-pressed-opacity": 0.32,
  "rmd-states-selected-opacity": 0.16,
  "rmd-states-theme-values": {
    "background-color": "#000",
    "dark-background-color": "#fff",
    "light-background-color": "#000",
    "hover-opacity": 0.08,
    "focus-opacity": 0.24,
    "pressed-opacity": 0.32,
    "selected-opacity": 0.16,
    "ripple-background-color": "rgba(0, 0, 0, 0.08)",
    "dark-ripple-background-color": "rgba(255, 255, 255, 0.08)",
    "light-ripple-background-color": "rgba(0, 0, 0, 0.08)",
    "ripple-opacity": 1,
  },
};
