/*
 * This file was generated from @react-md/dev-utils and should not be updated
 * manually.
 */

export default {
  "rmd-states-use-ripple": true,
  "rmd-states-use-pressed-states-fallback": true,
  "rmd-states-use-focus-shadow": true,
  "rmd-states-use-focus-background": true,
  "rmd-states-light-theme-background-color": "#000",
  "rmd-states-dark-theme-background-color": "#000",
  "rmd-states-light-theme-hover-color": "rgba(0, 0, 0, 0.08)",
  "rmd-states-light-theme-focus-color": "rgba(0, 0, 0, 0.24)",
  "rmd-states-light-theme-pressed-color": "rgba(0, 0, 0, 0.32)",
  "rmd-states-light-theme-selected-color": "rgba(0, 0, 0, 0.16)",
  "rmd-states-dark-theme-hover-color": "rgba(0, 0, 0, 0.04)",
  "rmd-states-dark-theme-focus-color": "rgba(0, 0, 0, 0.12)",
  "rmd-states-dark-theme-pressed-color": "rgba(0, 0, 0, 0.16)",
  "rmd-states-dark-theme-selected-color": "rgba(0, 0, 0, 0.12)",
  "rmd-states-light-theme-ripple-background-color": "rgba(0, 0, 0, 0.08)",
  "rmd-states-dark-theme-ripple-background-color": "rgba(0, 0, 0, 0.08)",
  "rmd-states-background-color": "#000",
  "rmd-states-hover-color": "rgba(0, 0, 0, 0.08)",
  "rmd-states-focus-color": "rgba(0, 0, 0, 0.24)",
  "rmd-states-pressed-color": "rgba(0, 0, 0, 0.32)",
  "rmd-states-selected-color": "rgba(0, 0, 0, 0.16)",
  "rmd-states-focus-shadow-width": "0.125rem",
  "rmd-states-focus-shadow-color": "#2196f3",
  "rmd-states-focus-shadow": "inset 0 0 0 0.125rem #2196f3",
  "rmd-states-ripple-background-color": "rgba(0, 0, 0, 0.08)",
  "rmd-states-ripple-transform-duration": "0.45s",
  "rmd-states-ripple-opacity-duration": "0.3s",
  "rmd-states-pressed-class-name": ".rmd-states--pressed",
  "rmd-states-theme-values": {
    "background-color": "transparent",
    "hover-color": "rgba(0, 0, 0, 0.08)",
    "focus-color": "rgba(0, 0, 0, 0.24)",
    "focus-shadow": "inset 0 0 0 0.125rem #2196f3",
    "pressed-color": "rgba(0, 0, 0, 0.32)",
    "selected-color": "rgba(0, 0, 0, 0.16)",
    "ripple-background-color": "rgba(0, 0, 0, 0.08)",
    "light-hover-color": "rgba(0, 0, 0, 0.08)",
    "light-focus-color": "rgba(0, 0, 0, 0.24)",
    "light-pressed-color": "rgba(0, 0, 0, 0.32)",
    "light-selected-color": "rgba(0, 0, 0, 0.16)",
    "light-ripple-background-color": "rgba(0, 0, 0, 0.08)",
    "dark-hover-color": "rgba(0, 0, 0, 0.04)",
    "dark-focus-color": "rgba(0, 0, 0, 0.12)",
    "dark-pressed-color": "rgba(0, 0, 0, 0.16)",
    "dark-selected-color": "rgba(0, 0, 0, 0.12)",
    "dark-ripple-background-color": "rgba(0, 0, 0, 0.08)",
  },
};
