/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const DomainVerificationIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function DomainVerificationIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path fill="none" d="M0 0h24v24H0z" />
        <path d="m16.6 10.88-1.42-1.42-4.24 4.25-2.12-2.13L7.4 13l3.54 3.54z" />
        <path d="M3 4v16h18V4H3zm16 14H5V8h14v10z" />
      </SVGIcon>
    );
  }
);
