// This was generated with a script
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const VARIABLE_LOOKUP: Record<string, Record<string, any>> = {
  alert: {
    "rmd-snackbar-margin": "1rem",
    "rmd-snackbar-z-index": 40,
    "rmd-toast-elevation": 6,
    "rmd-toast-border-radius": "0.25rem",
    "rmd-toast-light-background-color": "#323232",
    "rmd-toast-light-color": "#fff",
    "rmd-toast-dark-elevation-background-color": "#2c2c2c",
    "rmd-toast-dark-background-color": "#2c2c2c",
    "rmd-toast-dark-color": "#fff",
    "rmd-toast-background-color": "#323232",
    "rmd-toast-color": "#fff",
    "rmd-toast-min-height": "3rem",
    "rmd-toast-two-line-min-height": "4.25rem",
    "rmd-toast-min-width": "21.5rem",
    "rmd-toast-vertical-padding": "0.75rem",
    "rmd-toast-horizontal-padding": "1rem",
    "rmd-toast-action-margin": "0.5rem",
    "rmd-toast-stacked-action-margin-top": "0.25rem",
    "rmd-toast-enter-duration": "0.15s",
    "rmd-toast-exit-duration": "0.15s",
    "rmd-alert-theme-values": {
      "background-color": "#323232",
      color: "#fff",
      "light-background-color": "#323232",
      "light-color": "#fff",
      "dark-background-color": "#2c2c2c",
      "dark-color": "#fff",
    },
  },
  "app-bar": {
    "rmd-app-bar-z-index": 10,
    "rmd-app-bar-fixed-elevation": 2,
    "rmd-app-bar-height": "3.5rem",
    "rmd-app-bar-dense-height": "3rem",
    "rmd-app-bar-prominent-height": "7rem",
    "rmd-app-bar-prominent-dense-height": "6rem",
    "rmd-app-bar-keyline": "1rem",
    "rmd-app-bar-nav-margin": "0.25rem",
    "rmd-app-bar-title-keyline": "4.5rem",
    "rmd-app-bar-title-nav-margin": "1.25rem",
    "rmd-app-bar-lr-margin": "0.25rem",
    "rmd-app-bar-primary-background-color": "var(--rmd-theme-primary, #9c27b0)",
    "rmd-app-bar-primary-color": "var(--rmd-theme-on-primary, #fff)",
    "rmd-app-bar-secondary-background-color":
      "var(--rmd-theme-secondary, #f50057)",
    "rmd-app-bar-secondary-color": "var(--rmd-theme-on-secondary, #000)",
    "rmd-app-bar-default-light-theme-background-color": "#f5f5f5",
    "rmd-app-bar-default-light-theme-color": "#000",
    "rmd-app-bar-default-dark-theme-background-color": "#212121",
    "rmd-app-bar-default-dark-theme-color": "#fff",
    "rmd-app-bar-default-background-color": "#f5f5f5",
    "rmd-app-bar-default-color": "#000",
    "rmd-app-bar-theme-values": {
      "background-color": "transparent",
      color: "var(--rmd-theme-text-primary-on-background, #212121)",
      primary: "var(--rmd-theme-primary, #9c27b0)",
      "on-primary": "var(--rmd-theme-on-primary, #fff)",
      secondary: "var(--rmd-theme-secondary, #f50057)",
      "on-secondary": "var(--rmd-theme-on-secondary, #000)",
      "default-background-color": "#f5f5f5",
      "default-light-background-color": "#f5f5f5",
      "default-dark-background-color": "#212121",
      "default-color": "#000",
      "default-light-color": "#000",
      "default-dark-color": "#fff",
      height: "3.5rem",
      "dense-height": "3rem",
      "prominent-height": "7rem",
      "prominent-dense-height": "6rem",
    },
  },
  avatar: {
    "rmd-avatar-color": "#f5f5f5",
    "rmd-avatar-background-color": "#616161",
    "rmd-avatar-border-color": "rgba(0, 0, 0, 0.12)",
    "rmd-avatar-border-radius": "50%",
    "rmd-avatar-size": "2.5rem",
    "rmd-avatar-font-size": "1.5rem",
    "rmd-avatar-line-height": "1.75rem",
    "rmd-avatar-colors": {
      red: "#d50000 #ffebee",
      pink: "#d81b60 #fff",
      purple: "#7b1fa2 #e1bee7",
      "deep-purple": "#311b92 #d1c4e9",
      indigo: "#3949ab #c5cae9",
      blue: "#2962ff #fff",
      "light-blue": "#4fc3f7 #311b92",
      cyan: "#26c6da #004d40",
      teal: "#1de9b6 #004d40",
      green: "#2e7d32 #e8f5e9",
      "light-green": "#aed581 #1b5e20",
      lime: "#d4e157 #00695c",
      yellow: "#ff0 #795548",
      amber: "#ffca28 #4e342e",
      orange: "#fb8c00 #212121",
      "deep-orange": "#ff3d00 #212121",
      brown: "#795548 #efebe9",
      grey: "#616161 #f5f5f5",
      "blue-grey": "#455a64 #eceff1",
    },
    "rmd-avatar-theme-values": {
      "background-color": "#616161",
      "border-color": "rgba(0, 0, 0, 0.12)",
      "border-radius": "50%",
      color: "#f5f5f5",
      "font-size": "1.5rem",
      size: "2.5rem",
    },
  },
  badge: {
    "rmd-badge-size": "1.5rem",
    "rmd-badge-border-radius": "50%",
    "rmd-badge-default-background-color": "rgba(0, 0, 0, 0.2)",
    "rmd-badge-default-color": "#fff",
    "rmd-badge-font-size": "0.625rem",
    "rmd-badge-offset-top": 0,
    "rmd-badge-offset-right": 0,
    "rmd-badge-theme-values": {
      "background-color": "rgba(0, 0, 0, 0.2)",
      color: "#fff",
      "border-radius": "50%",
      "font-size": "0.625rem",
      size: "1.5rem",
      top: 0,
      right: 0,
    },
  },
  button: {
    "rmd-button-text-icon-inherit-color": true,
    "rmd-button-text-border-radius": "0.5rem",
    "rmd-button-text-horizontal-padding": "1rem",
    "rmd-button-text-vertical-padding": 0,
    "rmd-button-text-height": "2.25rem",
    "rmd-button-text-min-width": "4rem",
    "rmd-button-text-icon-size": "1.125rem",
    "rmd-button-icon-border-radius": "50%",
    "rmd-button-icon-size": "3rem",
    "rmd-button-outline-width": "1px",
    "rmd-button-box-shadow": "inset 0 0 0",
    "rmd-button-outline-color": "#999",
    "rmd-button-background-color": "transparent",
    "rmd-button-color": "var(--rmd-theme-text-primary-on-background, #212121)",
    "rmd-button-contained-elevation-transition-time": "0.15s",
    "rmd-button-contained-resting-elevation": 2,
    "rmd-button-contained-pressed-elevation": 4,
    "rmd-button-floating-z-index": 30,
    "rmd-button-floating-margin": "1.5rem",
    "rmd-button-circular-progress-size": "var(--rmd-icon-size, 1.5rem)",
    "rmd-button-floating-positions": {
      tl: { left: "1.5rem", top: "1.5rem" },
      tr: { right: "1.5rem", top: "1.5rem" },
      bl: { bottom: "1.5rem", left: "1.5rem" },
      br: { bottom: "1.5rem", right: "1.5rem" },
    },
    "rmd-button-theme-values": {
      "text-border-radius": "0.5rem",
      "text-horizontal-padding": "1rem",
      "text-vertical-padding": 0,
      "text-height": "2.25rem",
      "text-min-width": "4rem",
      "icon-border-radius": "50%",
      "icon-size": "3rem",
      "background-color": "transparent",
      color: "var(--rmd-theme-text-primary-on-background, #212121)",
      outline: "#999",
      "outline-width": "1px",
    },
  },
  card: {
    "rmd-card-elevation": 2,
    "rmd-card-light-background-color": "var(--rmd-theme-surface, #fff)",
    "rmd-card-dark-elevation-background-color": "#242424",
    "rmd-card-dark-background-color": "#242424",
    "rmd-card-background-color": "var(--rmd-theme-surface, #fff)",
    "rmd-card-color": "var(--rmd-theme-on-surface, #000)",
    "rmd-card-secondary-color":
      "var(--rmd-theme-text-primary-on-light, #212121)",
    "rmd-card-base-elevation": 1,
    "rmd-card-raised-elevation": 8,
    "rmd-card-border-radius": "0.25rem",
    "rmd-card-header-padding": "1rem",
    "rmd-card-header-padding-top": "1.5rem",
    "rmd-card-header-spacing": "1rem",
    "rmd-card-content-padding": "1rem",
    "rmd-card-content-padding-extra": "1.5rem",
    "rmd-card-actions-padding": "0.5rem",
    "rmd-card-border-color":
      "var(--rmd-divider-background-color, rgba(0, 0, 0, 0.12))",
    "rmd-card-border-width": "1px",
    "rmd-card-theme-values": {
      "background-color": "var(--rmd-theme-surface, #fff)",
      color: "var(--rmd-theme-on-surface, #000)",
      "secondary-color": "var(--rmd-theme-text-primary-on-light, #212121)",
    },
  },
  chip: {
    "rmd-chip-disable-focus-background-color": true,
    "rmd-chip-height": "2rem",
    "rmd-chip-border-radius": "1rem",
    "rmd-chip-small-spacing": "0.25rem",
    "rmd-chip-medium-spacing": "0.5rem",
    "rmd-chip-large-spacing": "0.75rem",
    "rmd-chip-icon-size": "1.125rem",
    "rmd-chip-avatar-size": "1.5rem",
    "rmd-chip-progress-size": "1.125rem",
    "rmd-chip-progress-width": 12,
    "rmd-chip-themed-background-color": "#ba68c8",
    "rmd-chip-themed-color": "#fff",
    "rmd-chip-solid-light-background-color": "#e0e0e0",
    "rmd-chip-solid-light-color": "#000",
    "rmd-chip-solid-light-disabled-background-color": "#f5f5f5",
    "rmd-chip-solid-dark-background-color": "#333",
    "rmd-chip-solid-dark-color": "#fff",
    "rmd-chip-solid-dark-disabled-background-color": "#262626",
    "rmd-chip-solid-background-color": "#e0e0e0",
    "rmd-chip-solid-color": "#000",
    "rmd-chip-solid-disabled-background-color": "#f5f5f5",
    "rmd-chip-outline-light-background-color": "#fff",
    "rmd-chip-outline-light-color": "#000",
    "rmd-chip-outline-dark-background-color": "#2f2f2f",
    "rmd-chip-outline-dark-color": "#fff",
    "rmd-chip-outline-background-color": "#fff",
    "rmd-chip-outline-color": "#000",
    "rmd-chip-outline-border-color": "#e0e0e0",
    "rmd-chip-transition-duration": "0.15s",
    "rmd-chip-box-shadow": "inset 0 0 0 1px",
    "rmd-chip-theme-values": {
      height: "2rem",
      "border-radius": "1rem",
      "themed-background-color": "#ba68c8",
      "themed-color": "#fff",
      "solid-background-color": "#e0e0e0",
      "solid-color": "#000",
      "solid-disabled": "#f5f5f5",
      "outline-background-color": "#fff",
      "outline-color": "#000",
      "outline-border-color": "#e0e0e0",
      "small-spacing": "0.25rem",
      "medium-spacing": "0.5rem",
      "large-spacing": "0.75rem",
    },
  },
  dialog: {
    "rmd-dialog-elevation": 16,
    "rmd-dialog-light-background-color": "var(--rmd-theme-surface, #fff)",
    "rmd-dialog-dark-elevation-background-color": "#353535",
    "rmd-dialog-dark-background-color": "#353535",
    "rmd-dialog-background-color": "var(--rmd-theme-surface, #fff)",
    "rmd-dialog-z-index": 30,
    "rmd-dialog-vertical-margin": "1.5rem",
    "rmd-dialog-horizontal-margin": "2.5rem",
    "rmd-dialog-header-padding": "1.5rem",
    "rmd-dialog-header-padding-bottom": "1.25rem",
    "rmd-dialog-content-padding": "1.5rem",
    "rmd-dialog-footer-padding": "0.5rem",
    "rmd-dialog-transition-distance": "1.875rem",
    "rmd-dialog-enter-duration": "0.2s",
    "rmd-dialog-leave-duration": "0.15s",
    "rmd-dialog-min-width": "17.5rem",
    "rmd-dialog-theme-values": {
      "background-color": "var(--rmd-theme-surface, #fff)",
      "horizontal-margin": "2.5rem",
      "vertical-margin": "1.5rem",
      "min-width": "17.5rem",
      "header-padding": "1.5rem",
      "header-padding-bottom": "1.25rem",
      "content-padding": "1.5rem",
      "footer-padding": "0.5rem",
      "z-index": 30,
    },
  },
  divider: {
    "rmd-divider-size": "1px",
    "rmd-divider-max-size": "100%",
    "rmd-divider-inset": "4rem",
    "rmd-divider-spacing": "0.25rem auto",
    "rmd-divider-vertical-spacing": "auto 0.25rem",
    "rmd-divider-background-color-on-light": "rgba(0, 0, 0, 0.12)",
    "rmd-divider-background-color-on-dark": "rgba(255, 255, 255, 0.12)",
    "rmd-divider-background-color": "rgba(0, 0, 0, 0.12)",
    "rmd-divider-theme-values": {
      "background-color": "rgba(0, 0, 0, 0.12)",
      "background-color-on-light": "rgba(0, 0, 0, 0.12)",
      "background-color-on-dark": "rgba(255, 255, 255, 0.12)",
      size: "1px",
      inset: "4rem",
      spacing: "0.25rem auto",
      "vertical-spacing": "auto 0.25rem",
      "max-size": "100%",
    },
  },
  elevation: {
    "rmd-elevation-color": "#000",
    "rmd-elevation-shadow-1-opacity": 0.2,
    "rmd-elevation-shadow-2-opacity": 0.14,
    "rmd-elevation-shadow-3-opacity": 0.12,
    "rmd-elevation-shadow-1-map": {
      "0": "0px 0px 0px 0px",
      "1": "0px 2px 1px -1px",
      "2": "0px 3px 1px -2px",
      "3": "0px 3px 3px -2px",
      "4": "0px 2px 4px -1px",
      "5": "0px 3px 5px -1px",
      "6": "0px 3px 5px -1px",
      "7": "0px 4px 5px -2px",
      "8": "0px 5px 5px -3px",
      "9": "0px 5px 6px -3px",
      "10": "0px 6px 6px -3px",
      "11": "0px 6px 7px -4px",
      "12": "0px 7px 8px -4px",
      "13": "0px 7px 8px -4px",
      "14": "0px 7px 9px -4px",
      "15": "0px 8px 9px -5px",
      "16": "0px 8px 10px -5px",
      "17": "0px 8px 11px -5px",
      "18": "0px 9px 11px -5px",
      "19": "0px 9px 12px -6px",
      "20": "0px 10px 13px -6px",
      "21": "0px 10px 13px -6px",
      "22": "0px 10px 14px -6px",
      "23": "0px 11px 14px -7px",
      "24": "0px 11px 15px -7px",
    },
    "rmd-elevation-shadow-2-map": {
      "0": "0px 0px 0px 0px",
      "1": "0px 1px 1px 0px",
      "2": "0px 2px 2px 0px",
      "3": "0px 3px 4px 0px",
      "4": "0px 4px 5px 0px",
      "5": "0px 5px 8px 0px",
      "6": "0px 6px 10px 0px",
      "7": "0px 7px 10px 1px",
      "8": "0px 8px 10px 1px",
      "9": "0px 9px 12px 1px",
      "10": "0px 10px 14px 1px",
      "11": "0px 11px 15px 1px",
      "12": "0px 12px 17px 2px",
      "13": "0px 13px 19px 2px",
      "14": "0px 14px 21px 2px",
      "15": "0px 15px 22px 2px",
      "16": "0px 16px 24px 2px",
      "17": "0px 17px 26px 2px",
      "18": "0px 18px 28px 2px",
      "19": "0px 19px 29px 2px",
      "20": "0px 20px 31px 3px",
      "21": "0px 21px 33px 3px",
      "22": "0px 22px 35px 3px",
      "23": "0px 23px 36px 3px",
      "24": "0px 24px 38px 3px",
    },
    "rmd-elevation-shadow-3-map": {
      "0": "0px 0px 0px 0px",
      "1": "0px 1px 3px 0px",
      "2": "0px 1px 5px 0px",
      "3": "0px 1px 8px 0px",
      "4": "0px 1px 10px 0px",
      "5": "0px 1px 14px 0px",
      "6": "0px 1px 18px 0px",
      "7": "0px 2px 16px 1px",
      "8": "0px 3px 14px 2px",
      "9": "0px 3px 16px 2px",
      "10": "0px 4px 18px 3px",
      "11": "0px 4px 20px 3px",
      "12": "0px 5px 22px 4px",
      "13": "0px 5px 24px 4px",
      "14": "0px 5px 26px 4px",
      "15": "0px 6px 28px 5px",
      "16": "0px 6px 30px 5px",
      "17": "0px 6px 32px 5px",
      "18": "0px 7px 34px 6px",
      "19": "0px 7px 36px 6px",
      "20": "0px 8px 38px 7px",
      "21": "0px 8px 40px 7px",
      "22": "0px 8px 42px 7px",
      "23": "0px 9px 44px 8px",
      "24": "0px 9px 46px 8px",
    },
  },
  "expansion-panel": {
    "rmd-expansion-panel-spacing": "1rem",
    "rmd-expansion-panel-header-padding": "1rem",
    "rmd-expansion-panel-expander-icon-spacing": "0.5rem",
    "rmd-expansion-panel-theme-values": {
      spacing: "1rem",
      padding: "1rem",
      "icon-spacing": "0.5rem",
    },
  },
  form: {
    "rmd-form-error-color": "#f44336",
    "rmd-form-error-hover-color": "#d50000",
    "rmd-form-active-color": "var(--rmd-theme-secondary, #f50057)",
    "rmd-form-disabled-color":
      "var(--rmd-theme-text-disabled-on-background, #9e9e9e)",
    "rmd-form-placeholder-color":
      "var(--rmd-theme-text-secondary-on-background, #757575)",
    "rmd-form-theme-values": {
      "error-color": "#f44336",
      "error-hover-color": "#d50000",
      "active-color": "var(--rmd-theme-secondary, #f50057)",
      "disabled-color": "var(--rmd-theme-text-disabled-on-background, #9e9e9e)",
      "toggle-inset": "0.3125rem",
      "toggle-dense-inset": "0.25rem",
      "indeterminate-height": "0.15rem",
      "indeterminate-dense-height": "0.125rem",
      "track-background-color": "#383838",
      "floating-top": "1rem",
      "floating-dense-top": "0.9rem",
      "addon-top": "auto",
      "addon-margin-top": "0px",
      "label-left-offset": "0px",
      "label-top-offset": "0px",
      "label-active-padding": "0px",
      "label-active-background-color": "transparent",
      "listbox-background-color": "var(--rmd-theme-surface, #fff)",
      "text-padding-left": "0px",
      "text-padding-right": "0px",
      "text-padding-top": "0px",
      "text-offset": "0px",
      "text-active-color": "#2196f3",
      "text-border-color": "rgba(0, 0, 0, 0.12)",
      "text-border-hover-color": "rgba(0, 0, 0, 0.87)",
      "text-filled-color": "#f5f5f5",
      "text-height": "3rem",
      "text-label-height": "3.5rem",
      "text-label-dense-height": "3.25rem",
      "text-placeholder-height": "3rem",
      "text-placeholder-dense-height": "2.5rem",
      "textarea-padding": "0.5rem",
    },
    "rmd-label-font-size": "1em",
    "rmd-label-floating-font-size": "0.75em",
    "rmd-label-floating-padding": "0.25rem",
    "rmd-label-floating-top": "1rem",
    "rmd-label-floating-dense-top": "0.9rem",
    "rmd-label-padding": "0.25rem",
    "rmd-select-native-multiple-padding": "0.75rem",
    "rmd-select-native-addon-top": "1rem",
    "rmd-listbox-elevation": 8,
    "rmd-listbox-light-background-color": "var(--rmd-theme-surface, #fff)",
    "rmd-listbox-dark-elevation-background-color": "#2f2f2f",
    "rmd-listbox-dark-background-color": "#2f2f2f",
    "rmd-listbox-background-color": "var(--rmd-theme-surface, #fff)",
    "rmd-listbox-z-index": 30,
    "rmd-option-focused-styles": { "box-shadow": "inset 0 0 0 2px #2196f3" },
    "rmd-option-selected-styles": {
      "background-color": "#0d47a1",
      color: "#fff",
    },
    "rmd-option-selected-offset": "0.5rem",
    "rmd-option-selected-content": "✓",
    "rmd-option-horizontal-padding": "1.5rem",
    "rmd-slider-include-vertical": true,
    "rmd-slider-size": "2rem",
    "rmd-slider-vertical-size": "15rem",
    "rmd-slider-active-track-size": "0.375rem",
    "rmd-slider-active-track-color": "var(--rmd-theme-secondary, #f50057)",
    "rmd-slider-active-track-opacity": null,
    "rmd-slider-inactive-track-size": "0.25rem",
    "rmd-slider-inactive-track-color": "var(--rmd-theme-secondary, #f50057)",
    "rmd-slider-disabled-track-color":
      "var(--rmd-theme-text-disabled-on-background, #9e9e9e)",
    "rmd-slider-disabled-thumb-color":
      "var(--rmd-theme-text-disabled-on-background, #9e9e9e)",
    "rmd-slider-inactive-track-opacity": 0.5,
    "rmd-slider-inactive-track-z-index": 1,
    "rmd-slider-active-track-z-index": 2,
    "rmd-slider-thumb-size": "1.25rem",
    "rmd-slider-thumb-radius": "50%",
    "rmd-slider-thumb-z-index": 2,
    "rmd-slider-thumb-bubble-opacity": 0.3,
    "rmd-slider-thumb-focus-scale": 2,
    "rmd-slider-thumb-active-scale": 2.5,
    "rmd-slider-thumb-disabled-scale": 0.5,
    "rmd-slider-thumb-disabled-mask-scale": 0.8,
    "rmd-slider-thumb-value-caret-size": "0.3rem",
    "rmd-slider-thumb-value-offset": "-1.75rem",
    "rmd-slider-container-padding": "1.25rem",
    "rmd-slider-container-addon-spacing": "1.25rem",
    "rmd-slider-theme-values": {
      size: "2rem",
      "vertical-size": "15rem",
      "active-size": "0.375rem",
      "inactive-size": "0.25rem",
      color: "var(--rmd-theme-secondary, #f50057)",
      "active-color": null,
      "inactive-color": null,
      "thumb-size": "1.25rem",
    },
    "rmd-text-field-active-color": "#2196f3",
    "rmd-text-field-light-border-color": "rgba(0, 0, 0, 0.12)",
    "rmd-text-field-dark-border-color": "rgba(255, 255, 255, 0.5)",
    "rmd-text-field-border-color": "rgba(0, 0, 0, 0.12)",
    "rmd-text-field-light-border-hover-color": "rgba(0, 0, 0, 0.87)",
    "rmd-text-field-dark-border-hover-color": "rgba(255, 255, 255, 0.87)",
    "rmd-text-field-border-hover-color": "rgba(0, 0, 0, 0.87)",
    "rmd-text-field-border-radius": "0.25rem",
    "rmd-text-field-border-width": "1px",
    "rmd-text-field-border-width-active": "2px",
    "rmd-text-field-label-height": "3.5rem",
    "rmd-text-field-label-dense-height": "3.25rem",
    "rmd-text-field-height": "3rem",
    "rmd-text-field-dense-height": "2.5rem",
    "rmd-text-field-outline-padding": "1rem",
    "rmd-text-field-underline-label-padding-top": "1rem",
    "rmd-text-field-underline-label-left-offset": "0.5rem",
    "rmd-text-field-underline-dense-padding-top": "0.25rem",
    "rmd-text-field-underline-padding": null,
    "rmd-text-field-filled-padding": "0.75rem",
    "rmd-text-field-filled-light-background-color": "#f5f5f5",
    "rmd-text-field-filled-dark-background-color": "#616161",
    "rmd-text-field-filled-background-color": "#f5f5f5",
    "rmd-text-field-filled-border-radius": "0.25rem",
    "rmd-text-field-addon-margin": "0.5rem",
    "rmd-textarea-vertical-padding": "0.5rem",
    "rmd-textarea-addon-top": "1rem",
    "rmd-form-message-min-height": "2rem",
    "rmd-form-message-margin-top": "0.5rem",
    "rmd-form-message-margin-bottom": "1rem",
    "rmd-form-message-counter-spacing": "0.5rem",
    "rmd-form-message-font-size": "0.75rem",
    "rmd-toggle-border-radius": "50%",
    "rmd-toggle-inset": "0.3125rem",
    "rmd-toggle-dense-inset": "0.25rem",
    "rmd-toggle-inactive-color":
      "var(--rmd-theme-text-secondary-on-background, #757575)",
    "rmd-toggle-active-color": "var(--rmd-theme-secondary, #f50057)",
    "rmd-checkbox-indeterminate-height": "0.15rem",
    "rmd-checkbox-indeterminate-dense-height": "0.125rem",
    "rmd-switch-track-height": "1rem",
    "rmd-switch-track-width": "2.25rem",
    "rmd-switch-track-background-color": "#383838",
    "rmd-switch-track-border-radius": "0.5rem",
    "rmd-switch-ball-size": "1.25rem",
    "rmd-switch-ball-border-radius": "50%",
    "rmd-switch-ball-offset": "0.25rem",
    "rmd-switch-container-vertical-padding": "0.5rem",
    "rmd-switch-container-horizontal-padding": "0.625rem",
    "rmd-switch-ball-disabled-color": "#f48fb1",
    "rmd-switch-progress-width": 12,
    "rmd-switch-progress-background-color": "#fff",
    "rmd-switch-progress-padding": "0.125rem",
  },
  icon: {
    "rmd-icon-color": "var(--rmd-theme-text-icon-on-background, #757575)",
    "rmd-icon-size": "1.5rem",
    "rmd-icon-dense-size": "1.25rem",
    "rmd-icon-include-dense": true,
    "rmd-icon-material-icons-font": false,
    "rmd-icon-use-font-icons": true,
    "rmd-icon-use-svg-icons": true,
    "rmd-icon-spacing-with-text": "0.5rem",
    "rmd-icon-rotator-transition-time": "0.15s",
    "rmd-icon-rotator-from": "rotate(0deg)",
    "rmd-icon-rotator-to": "rotate(180deg)",
    "rmd-icon-theme-values": {
      color: "var(--rmd-theme-text-icon-on-background, #757575)",
      size: "1.5rem",
      "dense-size": "1.25rem",
      "text-spacing": "0.5rem",
      "rotate-to": "rotate(180deg)",
      "rotate-from": "rotate(0deg)",
    },
  },
  layout: {
    "rmd-layout-enter-duration": "0.2s",
    "rmd-layout-leave-duration": "0.15s",
    "rmd-layout-main-focus-shadow": "inset 0 0 0 0.125rem #2196f3",
    "rmd-layout-main-focus-z-index": 999,
    "rmd-layout-navigation-z-index": 30,
    "rmd-layout-navigation-mini-z-index": 9,
    "rmd-layout-navigation-width": "16rem",
    "rmd-layout-mini-navigation-width": "3.5rem",
    "rmd-layout-theme-values": {
      "nav-width": "16rem",
      "mini-nav-width": "3.5rem",
      "main-offset": "var(--rmd-layout-nav-width, 16rem)",
    },
  },
  link: {
    "rmd-link-transition-time": "0.15s",
    "rmd-link-color": "#2196f3",
    "rmd-link-visited-color": "#1e88e5",
    "rmd-link-hover-color": "#42a5f5",
    "rmd-link-skip-z-index": 10000,
    "rmd-link-skip-styles": {
      color: "var(--rmd-theme-on-primary, #fff)",
      left: "50%",
      padding: "0.25rem 1rem",
      top: "0.25rem",
      transform: "translateX(-50%)",
    },
    "rmd-link-skip-active-styles": { outline: "0.25rem dashed #000" },
    "rmd-link-theme-values": {
      color: "#2196f3",
      "hover-color": "#42a5f5",
      "visited-color": "#1e88e5",
    },
  },
  list: {
    "rmd-list-vertical-padding": "0.5rem",
    "rmd-list-dense-vertical-padding": "0.25rem",
    "rmd-list-horizontal-padding": 0,
    "rmd-list-dense-horizontal-padding": 0,
    "rmd-list-line-height": "1.5rem",
    "rmd-list-font-size": "1rem",
    "rmd-list-dense-font-size": "0.8125rem",
    "rmd-list-item-vertical-padding": "0.5rem",
    "rmd-list-item-horizontal-padding": "1rem",
    "rmd-list-item-height": "3rem",
    "rmd-list-item-dense-height": "2.5rem",
    "rmd-list-item-medium-height": "3.5rem",
    "rmd-list-item-dense-medium-height": "3rem",
    "rmd-list-item-large-height": "4rem",
    "rmd-list-item-dense-large-height": "3.5rem",
    "rmd-list-item-extra-large-height": "4.5rem",
    "rmd-list-item-dense-extra-large-height": "4rem",
    "rmd-list-item-three-line-height": "5.5rem",
    "rmd-list-item-dense-three-line-height": "5rem",
    "rmd-list-item-secondary-text-line-height": 1.42857,
    "rmd-list-item-secondary-text-three-line-max-height": "3rem",
    "rmd-list-item-dense-secondary-text-three-line-max-height": "2.25rem",
    "rmd-list-item-text-keyline": "4.5rem",
    "rmd-list-item-media-size": "3.5rem",
    "rmd-list-item-media-large-size": "6.25rem",
    "rmd-list-item-media-spacing": "1rem",
    "rmd-list-item-disabled-opacity": 0.5,
    "rmd-list-theme-values": {
      "vertical-padding": "0.5rem",
      "horizontal-padding": 0,
      "font-size": "1rem",
      "text-keyline": "4.5rem",
      "item-height": "3rem",
      "item-medium-height": "3.5rem",
      "item-large-height": "4rem",
      "item-extra-large-height": "4.5rem",
      "item-three-line-height": "5.5rem",
      "item-vertical-padding": "0.5rem",
      "item-horizontal-padding": "1rem",
      "item-secondary-three-line-height": "3rem",
      "dense-font-size": "0.8125rem",
      "dense-vertical-padding": "0.25rem",
      "dense-horizontal-padding": 0,
      "dense-item-height": "2.5rem",
      "dense-item-medium-height": "3rem",
      "dense-item-large-height": "3.5rem",
      "dense-item-extra-large-height": "4rem",
      "dense-item-three-line-height": "5rem",
      "dense-item-secondary-three-line-height": "2.25rem",
      "media-size": "3.5rem",
      "media-spacing": "1rem",
      "media-large-size": "6.25rem",
    },
  },
  media: {
    "rmd-media-overlay-background-color": "rgba(0, 0, 0, 0.54)",
    "rmd-media-selectors": [
      "img",
      ">svg",
      "iframe",
      "video",
      "embed",
      "object",
    ],
    "rmd-media-default-aspect-ratio": "56.25%",
    "rmd-media-default-aspect-ratios": {
      '"16-9"': "16 9",
      '"4-3"': "4 3",
      '"1-1"': "1 1",
    },
    "rmd-media-overlay-padding": "1rem",
    "rmd-media-overlay-horizontal-width": "30%",
    "rmd-media-overlay-positions": [
      "top",
      "right",
      "bottom",
      "left",
      "middle",
      "center",
      "absolute-center",
    ],
  },
  menu: {
    "rmd-menu-elevation": 8,
    "rmd-menu-light-background-color": "var(--rmd-theme-surface, #fff)",
    "rmd-menu-dark-elevation-background-color": "#2f2f2f",
    "rmd-menu-dark-background-color": "#2f2f2f",
    "rmd-menu-background-color": "var(--rmd-theme-surface, #fff)",
    "rmd-menu-color": "var(--rmd-theme-on-surface, #000)",
    "rmd-menu-z-index": 30,
    "rmd-menu-min-width": "7rem",
    "rmd-menu-icon-spacing": "1rem",
    "rmd-menu-theme-values": {
      "background-color": "var(--rmd-theme-surface, #fff)",
      color: "var(--rmd-theme-on-surface, #000)",
      "min-width": "7rem",
      "icon-spacing": "1rem",
      "z-index": 30,
    },
  },
  overlay: {
    "rmd-overlay-z-index": 30,
    "rmd-overlay-transition-duration": "0.15s",
    "rmd-overlay-color": "rgba(0, 0, 0, 0.4)",
    "rmd-overlay-theme-values": {
      "background-color": "rgba(0, 0, 0, 0.4)",
      "active-opacity": 1,
      "z-index": 30,
    },
  },
  progress: {
    "rmd-progress-include-linear": true,
    "rmd-progress-include-circular": true,
    "rmd-progress-color": "#9c27b0",
    "rmd-progress-background-color": "#ba68c8",
    "rmd-linear-progress-size": "0.25rem",
    "rmd-linear-progress-transition-duration": "2.4s",
    "rmd-linear-progress-short-animation-delay": "0.75s",
    "rmd-linear-progress-styles": {
      "0%": { left: "-35%", right: "100%" },
      "60%": { left: "100%", right: "-90%" },
      "100%": { left: "100%", right: "-90%" },
    },
    "rmd-linear-progress-short-styles": {
      "0%": { left: "-200%", right: "100%" },
      "40%": { left: "107%", right: "-8%" },
      "100%": { left: "107%", right: "-8%" },
    },
    "rmd-linear-progress-reverse-styles": {
      "0%": { left: "100%", right: "-35%" },
      "60%": { left: "-90%", right: "100%" },
      "100%": { left: "-90%", right: "100%" },
    },
    "rmd-linear-progress-reverse-short-styles": {
      "0%": { left: "100%", right: "-200%" },
      "40%": { left: "-8%", right: "107%" },
      "100%": { left: "-8%", right: "107%" },
    },
    "rmd-linear-progress-vertical-styles": {
      "0%": { bottom: "-35%", top: "100%" },
      "60%": { bottom: "100%", top: "-90%" },
      "100%": { bottom: "100%", top: "-90%" },
    },
    "rmd-linear-progress-vertical-short-styles": {
      "0%": { bottom: "-200%", top: "100%" },
      "40%": { bottom: "107%", top: "-8%" },
      "100%": { bottom: "107%", top: "-8%" },
    },
    "rmd-linear-progress-vertical-reverse-styles": {
      "0%": { bottom: "100%", top: "-35%" },
      "60%": { bottom: "-90%", top: "100%" },
      "100%": { bottom: "-90%", top: "100%" },
    },
    "rmd-linear-progress-vertical-reverse-short-styles": {
      "0%": { bottom: "100%", top: "-200%" },
      "40%": { bottom: "-8%", top: "107%" },
      "100%": { bottom: "-8%", top: "107%" },
    },
    "rmd-circular-progress-size": "3rem",
    "rmd-circular-progress-small-size": "1.5rem",
    "rmd-circular-progress-stroke-width": 6,
    "rmd-circular-progress-dasharray": 187,
    "rmd-circular-progress-transition-duration": "2.4s",
    "rmd-circular-progress-start-offset": 187,
    "rmd-circular-progress-end-offset": 46.75,
    "rmd-circular-progress-rotate-styles": {
      "0%": { transform: "rotate(0deg)" },
      "50%": { transform: "rotate(135deg)" },
      "75%": { transform: "rotate(450deg)" },
      "100%": { transform: "rotate(720deg)" },
    },
    "rmd-circular-progress-dash-styles": {
      "0%": { "stroke-dashoffset": 187 },
      "50%": { "stroke-dashoffset": 46.75 },
      "100%": { "stroke-dashoffset": 187 },
    },
    "rmd-progress-theme-values": {
      color: "#9c27b0",
      "background-color": "#ba68c8",
      "linear-size": "0.25rem",
      "circular-size": "3rem",
      "circular-width": 6,
    },
  },
  sheet: {
    "rmd-sheet-z-index": 5,
    "rmd-sheet-raised-z-index": 30,
    "rmd-sheet-overlay-z-index": 30,
    "rmd-sheet-elevation": 2,
    "rmd-sheet-raised-elevation": 16,
    "rmd-sheet-light-background-color":
      "var(--rmd-dialog-background-color, var(--rmd-theme-surface, #fff))",
    "rmd-sheet-dark-elevation-background-color": "#242424",
    "rmd-sheet-dark-background-color": "#242424",
    "rmd-sheet-background-color":
      "var(--rmd-dialog-background-color, var(--rmd-theme-surface, #fff))",
    "rmd-sheet-raised-light-background-color":
      "var(--rmd-dialog-background-color, var(--rmd-theme-surface, #fff))",
    "rmd-sheet-raised-dark-elevation-background-color": "#353535",
    "rmd-sheet-raised-dark-background-color": "#353535",
    "rmd-sheet-raised-background-color":
      "var(--rmd-dialog-background-color, var(--rmd-theme-surface, #fff))",
    "rmd-sheet-enter-duration": "0.2s",
    "rmd-sheet-leave-duration": "0.15s",
    "rmd-sheet-touch-margin": "3.5rem",
    "rmd-sheet-touch-width": "calc(100vw - 3.5rem)",
    "rmd-sheet-static-width": "16rem",
    "rmd-sheet-max-height": "100%",
    "rmd-sheet-touchable-max-height": "calc(100% - 3.5rem)",
    "rmd-sheet-recommended-min-height": "3.5rem",
    "rmd-sheet-recommended-max-height": "50%",
    "rmd-sheet-positions": ["top", "right", "bottom", "left"],
    "rmd-sheet-enabled-positions": ["top", "right", "bottom", "left"],
    "rmd-sheet-theme-values": {
      "background-color":
        "var(--rmd-dialog-background-color, var(--rmd-theme-surface, #fff))",
      "raised-background-color":
        "var(--rmd-dialog-background-color, var(--rmd-theme-surface, #fff))",
      "touch-width": "calc(100vw - 3.5rem)",
      "static-width": "16rem",
      "touchable-max-height": "calc(100% - 3.5rem)",
      "max-height": null,
      height: null,
      width: null,
      "transform-offscreen": null,
    },
  },
  states: {
    "rmd-states-use-ripple": true,
    "rmd-states-use-pressed-states-fallback": true,
    "rmd-states-use-focus-shadow": true,
    "rmd-states-use-focus-background": true,
    "rmd-states-light-theme-background-color": "#000",
    "rmd-states-dark-theme-background-color": "#000",
    "rmd-states-light-theme-hover-color": "rgba(0, 0, 0, 0.08)",
    "rmd-states-light-theme-focus-color": "rgba(0, 0, 0, 0.24)",
    "rmd-states-light-theme-pressed-color": "rgba(0, 0, 0, 0.32)",
    "rmd-states-light-theme-selected-color": "rgba(0, 0, 0, 0.16)",
    "rmd-states-dark-theme-hover-color": "rgba(0, 0, 0, 0.04)",
    "rmd-states-dark-theme-focus-color": "rgba(0, 0, 0, 0.12)",
    "rmd-states-dark-theme-pressed-color": "rgba(0, 0, 0, 0.16)",
    "rmd-states-dark-theme-selected-color": "rgba(0, 0, 0, 0.12)",
    "rmd-states-light-theme-ripple-background-color": "rgba(0, 0, 0, 0.08)",
    "rmd-states-dark-theme-ripple-background-color": "rgba(0, 0, 0, 0.08)",
    "rmd-states-background-color": "#000",
    "rmd-states-hover-color": "rgba(0, 0, 0, 0.08)",
    "rmd-states-focus-color": "rgba(0, 0, 0, 0.24)",
    "rmd-states-pressed-color": "rgba(0, 0, 0, 0.32)",
    "rmd-states-selected-color": "rgba(0, 0, 0, 0.16)",
    "rmd-states-focus-shadow-width": "0.125rem",
    "rmd-states-focus-shadow-color": "#2196f3",
    "rmd-states-focus-shadow": "inset 0 0 0 0.125rem #2196f3",
    "rmd-states-ripple-background-color": "rgba(0, 0, 0, 0.08)",
    "rmd-states-ripple-transform-duration": "0.45s",
    "rmd-states-ripple-opacity-duration": "0.3s",
    "rmd-states-pressed-class-name": ".rmd-states--pressed",
    "rmd-states-theme-values": {
      "background-color": "transparent",
      "hover-color": "rgba(0, 0, 0, 0.08)",
      "focus-color": "rgba(0, 0, 0, 0.24)",
      "focus-shadow": "inset 0 0 0 0.125rem #2196f3",
      "pressed-color": "rgba(0, 0, 0, 0.32)",
      "selected-color": "rgba(0, 0, 0, 0.16)",
      "ripple-background-color": "rgba(0, 0, 0, 0.08)",
      "light-hover-color": "rgba(0, 0, 0, 0.08)",
      "light-focus-color": "rgba(0, 0, 0, 0.24)",
      "light-pressed-color": "rgba(0, 0, 0, 0.32)",
      "light-selected-color": "rgba(0, 0, 0, 0.16)",
      "light-ripple-background-color": "rgba(0, 0, 0, 0.08)",
      "dark-hover-color": "rgba(0, 0, 0, 0.04)",
      "dark-focus-color": "rgba(0, 0, 0, 0.12)",
      "dark-pressed-color": "rgba(0, 0, 0, 0.16)",
      "dark-selected-color": "rgba(0, 0, 0, 0.12)",
      "dark-ripple-background-color": "rgba(0, 0, 0, 0.08)",
    },
  },
  table: {
    "rmd-table-light-border-color": "#e0e0e0",
    "rmd-table-dark-border-color": "#2f2f2f",
    "rmd-table-border-color": "#e0e0e0",
    "rmd-table-cell-horizontal-padding": "1rem",
    "rmd-table-cell-vertical-padding": "0.375rem",
    "rmd-table-cell-sticky-position": 0,
    "rmd-table-cell-sticky-z-index": 2,
    "rmd-table-cell-height": "3.25rem",
    "rmd-table-cell-dense-height": "2rem",
    "rmd-table-cell-color":
      "var(--rmd-theme-text-primary-on-background, #212121)",
    "rmd-table-cell-horizontal-alignments": ["center", "right"],
    "rmd-table-cell-vertical-alignments": ["top", "bottom"],
    "rmd-table-header-cell-height": "3.5rem",
    "rmd-table-header-cell-dense-height": "2.125rem",
    "rmd-table-header-cell-color":
      "var(--rmd-theme-text-primary-on-background, #212121)",
    "rmd-table-header-sticky-position": 0,
    "rmd-table-row-hover-color": "rgba(0, 0, 0, 0.12)",
    "rmd-table-row-selected-color":
      "var(--rmd-states-selected-color, rgba(0, 0, 0, 0.16))",
    "rmd-table-footer-sticky-position": 0,
    "rmd-table-checkbox-padding": "0.5rem",
    "rmd-table-theme-values": {
      "border-color": "#e0e0e0",
      "cell-color": "var(--rmd-theme-text-primary-on-background, #212121)",
      "cell-h-padding": "1rem",
      "cell-v-padding": "0.375rem",
      "cell-height": "3.25rem",
      "cell-dense-height": "2rem",
      "hover-color": "rgba(0, 0, 0, 0.12)",
      "selected-color": "var(--rmd-states-selected-color, rgba(0, 0, 0, 0.16))",
      "sticky-header": 0,
      "sticky-cell": 0,
      "sticky-footer": 0,
    },
  },
  tabs: {
    "rmd-tab-height": "3rem",
    "rmd-tab-stacked-height": "4.5rem",
    "rmd-tab-horizontal-padding": "1rem",
    "rmd-tab-vertical-padding": "0.75rem",
    "rmd-tab-min-width": "5.625rem",
    "rmd-tab-max-width": "20rem",
    "rmd-tab-indicator-color": "var(--rmd-theme-primary, #9c27b0)",
    "rmd-tab-active-color": "#212121",
    "rmd-tab-inactive-color": "#757575",
    "rmd-tab-disabled-color": "#9e9e9e",
    "rmd-tab-active-indicator-height": "0.125rem",
    "rmd-tabs-positions": ["left", "center", "right"],
    "rmd-tabs-scrollable-padding": "3.25rem",
    "rmd-tabs-theme-values": {
      active: "#212121",
      inactive: "#757575",
      disabled: "#9e9e9e",
      "indicator-color": "var(--rmd-theme-primary, #9c27b0)",
    },
  },
  theme: {
    "rmd-theme-default-contrast-ratio": 3,
    "rmd-theme-better-contrast-colors": true,
    "rmd-red-50": "#ffebee",
    "rmd-red-100": "#ffcdd2",
    "rmd-red-200": "#ef9a9a",
    "rmd-red-300": "#e57373",
    "rmd-red-400": "#ef5350",
    "rmd-red-500": "#f44336",
    "rmd-red-600": "#e53935",
    "rmd-red-700": "#d32f2f",
    "rmd-red-800": "#c62828",
    "rmd-red-900": "#b71c1c",
    "rmd-red-a-100": "#ff8a80",
    "rmd-red-a-200": "#ff5252",
    "rmd-red-a-400": "#ff1744",
    "rmd-red-a-700": "#d50000",
    "rmd-pink-50": "#fce4ec",
    "rmd-pink-100": "#f8bbd0",
    "rmd-pink-200": "#f48fb1",
    "rmd-pink-300": "#f06292",
    "rmd-pink-400": "#ec407a",
    "rmd-pink-500": "#e91e63",
    "rmd-pink-600": "#d81b60",
    "rmd-pink-700": "#c2185b",
    "rmd-pink-800": "#ad1457",
    "rmd-pink-900": "#880e4f",
    "rmd-pink-a-100": "#ff80ab",
    "rmd-pink-a-200": "#ff4081",
    "rmd-pink-a-400": "#f50057",
    "rmd-pink-a-700": "#c51162",
    "rmd-purple-50": "#f3e5f5",
    "rmd-purple-100": "#e1bee7",
    "rmd-purple-200": "#ce93d8",
    "rmd-purple-300": "#ba68c8",
    "rmd-purple-400": "#ab47bc",
    "rmd-purple-500": "#9c27b0",
    "rmd-purple-600": "#8e24aa",
    "rmd-purple-700": "#7b1fa2",
    "rmd-purple-800": "#6a1b9a",
    "rmd-purple-900": "#4a148c",
    "rmd-purple-a-100": "#ea80fc",
    "rmd-purple-a-200": "#e040fb",
    "rmd-purple-a-400": "#d500f9",
    "rmd-purple-a-700": "#a0f",
    "rmd-deep-purple-50": "#ede7f6",
    "rmd-deep-purple-100": "#d1c4e9",
    "rmd-deep-purple-200": "#b39ddb",
    "rmd-deep-purple-300": "#9575cd",
    "rmd-deep-purple-400": "#7e57c2",
    "rmd-deep-purple-500": "#673ab7",
    "rmd-deep-purple-600": "#5e35b1",
    "rmd-deep-purple-700": "#512da8",
    "rmd-deep-purple-800": "#4527a0",
    "rmd-deep-purple-900": "#311b92",
    "rmd-deep-purple-a-100": "#b388ff",
    "rmd-deep-purple-a-200": "#7c4dff",
    "rmd-deep-purple-a-400": "#651fff",
    "rmd-deep-purple-a-700": "#6200ea",
    "rmd-indigo-50": "#e8eaf6",
    "rmd-indigo-100": "#c5cae9",
    "rmd-indigo-200": "#9fa8da",
    "rmd-indigo-300": "#7986cb",
    "rmd-indigo-400": "#5c6bc0",
    "rmd-indigo-500": "#3f51b5",
    "rmd-indigo-600": "#3949ab",
    "rmd-indigo-700": "#303f9f",
    "rmd-indigo-800": "#283593",
    "rmd-indigo-900": "#1a237e",
    "rmd-indigo-a-100": "#8c9eff",
    "rmd-indigo-a-200": "#536dfe",
    "rmd-indigo-a-400": "#3d5afe",
    "rmd-indigo-a-700": "#304ffe",
    "rmd-blue-50": "#e3f2fd",
    "rmd-blue-100": "#bbdefb",
    "rmd-blue-200": "#90caf9",
    "rmd-blue-300": "#64b5f6",
    "rmd-blue-400": "#42a5f5",
    "rmd-blue-500": "#2196f3",
    "rmd-blue-600": "#1e88e5",
    "rmd-blue-700": "#1976d2",
    "rmd-blue-800": "#1565c0",
    "rmd-blue-900": "#0d47a1",
    "rmd-blue-a-100": "#82b1ff",
    "rmd-blue-a-200": "#448aff",
    "rmd-blue-a-400": "#2979ff",
    "rmd-blue-a-700": "#2962ff",
    "rmd-light-blue-50": "#e1f5fe",
    "rmd-light-blue-100": "#b3e5fc",
    "rmd-light-blue-200": "#81d4fa",
    "rmd-light-blue-300": "#4fc3f7",
    "rmd-light-blue-400": "#29b6f6",
    "rmd-light-blue-500": "#03a9f4",
    "rmd-light-blue-600": "#039be5",
    "rmd-light-blue-700": "#0288d1",
    "rmd-light-blue-800": "#0277bd",
    "rmd-light-blue-900": "#01579b",
    "rmd-light-blue-a-100": "#80d8ff",
    "rmd-light-blue-a-200": "#40c4ff",
    "rmd-light-blue-a-400": "#00b0ff",
    "rmd-light-blue-a-700": "#0091ea",
    "rmd-cyan-50": "#e0f7fa",
    "rmd-cyan-100": "#b2ebf2",
    "rmd-cyan-200": "#80deea",
    "rmd-cyan-300": "#4dd0e1",
    "rmd-cyan-400": "#26c6da",
    "rmd-cyan-500": "#00bcd4",
    "rmd-cyan-600": "#00acc1",
    "rmd-cyan-700": "#0097a7",
    "rmd-cyan-800": "#00838f",
    "rmd-cyan-900": "#006064",
    "rmd-cyan-a-100": "#84ffff",
    "rmd-cyan-a-200": "#18ffff",
    "rmd-cyan-a-400": "#00e5ff",
    "rmd-cyan-a-700": "#00b8d4",
    "rmd-teal-50": "#e0f2f1",
    "rmd-teal-100": "#b2dfdb",
    "rmd-teal-200": "#80cbc4",
    "rmd-teal-300": "#4db6ac",
    "rmd-teal-400": "#26a69a",
    "rmd-teal-500": "#009688",
    "rmd-teal-600": "#00897b",
    "rmd-teal-700": "#00796b",
    "rmd-teal-800": "#00695c",
    "rmd-teal-900": "#004d40",
    "rmd-teal-a-100": "#a7ffeb",
    "rmd-teal-a-200": "#64ffda",
    "rmd-teal-a-400": "#1de9b6",
    "rmd-teal-a-700": "#00bfa5",
    "rmd-green-50": "#e8f5e9",
    "rmd-green-100": "#c8e6c9",
    "rmd-green-200": "#a5d6a7",
    "rmd-green-300": "#81c784",
    "rmd-green-400": "#66bb6a",
    "rmd-green-500": "#4caf50",
    "rmd-green-600": "#43a047",
    "rmd-green-700": "#388e3c",
    "rmd-green-800": "#2e7d32",
    "rmd-green-900": "#1b5e20",
    "rmd-green-a-100": "#b9f6ca",
    "rmd-green-a-200": "#69f0ae",
    "rmd-green-a-400": "#00e676",
    "rmd-green-a-700": "#00c853",
    "rmd-light-green-50": "#f1f8e9",
    "rmd-light-green-100": "#dcedc8",
    "rmd-light-green-200": "#c5e1a5",
    "rmd-light-green-300": "#aed581",
    "rmd-light-green-400": "#9ccc65",
    "rmd-light-green-500": "#8bc34a",
    "rmd-light-green-600": "#7cb342",
    "rmd-light-green-700": "#689f38",
    "rmd-light-green-800": "#558b2f",
    "rmd-light-green-900": "#33691e",
    "rmd-light-green-a-100": "#ccff90",
    "rmd-light-green-a-200": "#b2ff59",
    "rmd-light-green-a-400": "#76ff03",
    "rmd-light-green-a-700": "#64dd17",
    "rmd-lime-50": "#f9fbe7",
    "rmd-lime-100": "#f0f4c3",
    "rmd-lime-200": "#e6ee9c",
    "rmd-lime-300": "#dce775",
    "rmd-lime-400": "#d4e157",
    "rmd-lime-500": "#cddc39",
    "rmd-lime-600": "#c0ca33",
    "rmd-lime-700": "#afb42b",
    "rmd-lime-800": "#9e9d24",
    "rmd-lime-900": "#827717",
    "rmd-lime-a-100": "#f4ff81",
    "rmd-lime-a-200": "#eeff41",
    "rmd-lime-a-400": "#c6ff00",
    "rmd-lime-a-700": "#aeea00",
    "rmd-yellow-50": "#fffde7",
    "rmd-yellow-100": "#fff9c4",
    "rmd-yellow-200": "#fff59d",
    "rmd-yellow-300": "#fff176",
    "rmd-yellow-400": "#ffee58",
    "rmd-yellow-500": "#ffeb3b",
    "rmd-yellow-600": "#fdd835",
    "rmd-yellow-700": "#fbc02d",
    "rmd-yellow-800": "#f9a825",
    "rmd-yellow-900": "#f57f17",
    "rmd-yellow-a-100": "#ffff8d",
    "rmd-yellow-a-200": "#ff0",
    "rmd-yellow-a-400": "#ffea00",
    "rmd-yellow-a-700": "#ffd600",
    "rmd-amber-50": "#fff8e1",
    "rmd-amber-100": "#ffecb3",
    "rmd-amber-200": "#ffe082",
    "rmd-amber-300": "#ffd54f",
    "rmd-amber-400": "#ffca28",
    "rmd-amber-500": "#ffc107",
    "rmd-amber-600": "#ffb300",
    "rmd-amber-700": "#ffa000",
    "rmd-amber-800": "#ff8f00",
    "rmd-amber-900": "#ff6f00",
    "rmd-amber-a-100": "#ffe57f",
    "rmd-amber-a-200": "#ffd740",
    "rmd-amber-a-400": "#ffc400",
    "rmd-amber-a-700": "#ffab00",
    "rmd-orange-50": "#fff3e0",
    "rmd-orange-100": "#fff0b2",
    "rmd-orange-200": "#ffcc80",
    "rmd-orange-300": "#ffb74d",
    "rmd-orange-400": "#ffa726",
    "rmd-orange-500": "#ff9800",
    "rmd-orange-600": "#fb8c00",
    "rmd-orange-700": "#f57c00",
    "rmd-orange-800": "#ef6c00",
    "rmd-orange-900": "#e65100",
    "rmd-orange-a-100": "#ffd180",
    "rmd-orange-a-200": "#ffab40",
    "rmd-orange-a-400": "#ff9100",
    "rmd-orange-a-700": "#ff6d00",
    "rmd-deep-orange-50": "#fbe9e7",
    "rmd-deep-orange-100": "#ffccbc",
    "rmd-deep-orange-200": "#ffab91",
    "rmd-deep-orange-300": "#ff8a65",
    "rmd-deep-orange-400": "#ff7043",
    "rmd-deep-orange-500": "#ff5722",
    "rmd-deep-orange-600": "#f4511e",
    "rmd-deep-orange-700": "#e64a19",
    "rmd-deep-orange-800": "#d84315",
    "rmd-deep-orange-900": "#bf360c",
    "rmd-deep-orange-a-100": "#ff9e80",
    "rmd-deep-orange-a-200": "#ff6e40",
    "rmd-deep-orange-a-400": "#ff3d00",
    "rmd-deep-orange-a-700": "#dd2c00",
    "rmd-brown-50": "#efebe9",
    "rmd-brown-100": "#d7ccc8",
    "rmd-brown-200": "#bcaaa4",
    "rmd-brown-300": "#a1887f",
    "rmd-brown-400": "#8d6e63",
    "rmd-brown-500": "#795548",
    "rmd-brown-600": "#6d4c41",
    "rmd-brown-700": "#5d4037",
    "rmd-brown-800": "#4e342e",
    "rmd-brown-900": "#3e2723",
    "rmd-grey-50": "#fafafa",
    "rmd-grey-100": "#f5f5f5",
    "rmd-grey-200": "#eee",
    "rmd-grey-300": "#e0e0e0",
    "rmd-grey-400": "#bdbdbd",
    "rmd-grey-500": "#9e9e9e",
    "rmd-grey-600": "#757575",
    "rmd-grey-700": "#616161",
    "rmd-grey-800": "#424242",
    "rmd-grey-900": "#212121",
    "rmd-blue-grey-50": "#eceff1",
    "rmd-blue-grey-100": "#cfd8dc",
    "rmd-blue-grey-200": "#b0bec5",
    "rmd-blue-grey-300": "#90a4ae",
    "rmd-blue-grey-400": "#78909c",
    "rmd-blue-grey-500": "#607d8b",
    "rmd-blue-grey-600": "#546e7a",
    "rmd-blue-grey-700": "#455a64",
    "rmd-blue-grey-800": "#37474f",
    "rmd-blue-grey-900": "#263238",
    "rmd-black-base": "#000",
    "rmd-white-base": "#fff",
    "rmd-theme-color-map": {
      "rmd-red-50": "#ffebee",
      "rmd-red-100": "#ffcdd2",
      "rmd-red-200": "#ef9a9a",
      "rmd-red-300": "#e57373",
      "rmd-red-400": "#ef5350",
      "rmd-red-500": "#f44336",
      "rmd-red-600": "#e53935",
      "rmd-red-700": "#d32f2f",
      "rmd-red-800": "#c62828",
      "rmd-red-900": "#b71c1c",
      "rmd-red-a-100": "#ff8a80",
      "rmd-red-a-200": "#ff5252",
      "rmd-red-a-400": "#ff1744",
      "rmd-red-a-700": "#d50000",
      "rmd-pink-50": "#fce4ec",
      "rmd-pink-100": "#f8bbd0",
      "rmd-pink-200": "#f48fb1",
      "rmd-pink-300": "#f06292",
      "rmd-pink-400": "#ec407a",
      "rmd-pink-500": "#e91e63",
      "rmd-pink-600": "#d81b60",
      "rmd-pink-700": "#c2185b",
      "rmd-pink-800": "#ad1457",
      "rmd-pink-900": "#880e4f",
      "rmd-pink-a-100": "#ff80ab",
      "rmd-pink-a-200": "#ff4081",
      "rmd-pink-a-400": "#f50057",
      "rmd-pink-a-700": "#c51162",
      "rmd-purple-50": "#f3e5f5",
      "rmd-purple-100": "#e1bee7",
      "rmd-purple-200": "#ce93d8",
      "rmd-purple-300": "#ba68c8",
      "rmd-purple-400": "#ab47bc",
      "rmd-purple-500": "#9c27b0",
      "rmd-purple-600": "#8e24aa",
      "rmd-purple-700": "#7b1fa2",
      "rmd-purple-800": "#6a1b9a",
      "rmd-purple-900": "#4a148c",
      "rmd-purple-a-100": "#ea80fc",
      "rmd-purple-a-200": "#e040fb",
      "rmd-purple-a-400": "#d500f9",
      "rmd-purple-a-700": "#a0f",
      "rmd-deep-purple-50": "#ede7f6",
      "rmd-deep-purple-100": "#d1c4e9",
      "rmd-deep-purple-200": "#b39ddb",
      "rmd-deep-purple-300": "#9575cd",
      "rmd-deep-purple-400": "#7e57c2",
      "rmd-deep-purple-500": "#673ab7",
      "rmd-deep-purple-600": "#5e35b1",
      "rmd-deep-purple-700": "#512da8",
      "rmd-deep-purple-800": "#4527a0",
      "rmd-deep-purple-900": "#311b92",
      "rmd-deep-purple-a-100": "#b388ff",
      "rmd-deep-purple-a-200": "#7c4dff",
      "rmd-deep-purple-a-400": "#651fff",
      "rmd-deep-purple-a-700": "#6200ea",
      "rmd-indigo-50": "#e8eaf6",
      "rmd-indigo-100": "#c5cae9",
      "rmd-indigo-200": "#9fa8da",
      "rmd-indigo-300": "#7986cb",
      "rmd-indigo-400": "#5c6bc0",
      "rmd-indigo-500": "#3f51b5",
      "rmd-indigo-600": "#3949ab",
      "rmd-indigo-700": "#303f9f",
      "rmd-indigo-800": "#283593",
      "rmd-indigo-900": "#1a237e",
      "rmd-indigo-a-100": "#8c9eff",
      "rmd-indigo-a-200": "#536dfe",
      "rmd-indigo-a-400": "#3d5afe",
      "rmd-indigo-a-700": "#304ffe",
      "rmd-blue-50": "#e3f2fd",
      "rmd-blue-100": "#bbdefb",
      "rmd-blue-200": "#90caf9",
      "rmd-blue-300": "#64b5f6",
      "rmd-blue-400": "#42a5f5",
      "rmd-blue-500": "#2196f3",
      "rmd-blue-600": "#1e88e5",
      "rmd-blue-700": "#1976d2",
      "rmd-blue-800": "#1565c0",
      "rmd-blue-900": "#0d47a1",
      "rmd-blue-a-100": "#82b1ff",
      "rmd-blue-a-200": "#448aff",
      "rmd-blue-a-400": "#2979ff",
      "rmd-blue-a-700": "#2962ff",
      "rmd-light-blue-50": "#e1f5fe",
      "rmd-light-blue-100": "#b3e5fc",
      "rmd-light-blue-200": "#81d4fa",
      "rmd-light-blue-300": "#4fc3f7",
      "rmd-light-blue-400": "#29b6f6",
      "rmd-light-blue-500": "#03a9f4",
      "rmd-light-blue-600": "#039be5",
      "rmd-light-blue-700": "#0288d1",
      "rmd-light-blue-800": "#0277bd",
      "rmd-light-blue-900": "#01579b",
      "rmd-light-blue-a-100": "#80d8ff",
      "rmd-light-blue-a-200": "#40c4ff",
      "rmd-light-blue-a-400": "#00b0ff",
      "rmd-light-blue-a-700": "#0091ea",
      "rmd-cyan-50": "#e0f7fa",
      "rmd-cyan-100": "#b2ebf2",
      "rmd-cyan-200": "#80deea",
      "rmd-cyan-300": "#4dd0e1",
      "rmd-cyan-400": "#26c6da",
      "rmd-cyan-500": "#00bcd4",
      "rmd-cyan-600": "#00acc1",
      "rmd-cyan-700": "#0097a7",
      "rmd-cyan-800": "#00838f",
      "rmd-cyan-900": "#006064",
      "rmd-cyan-a-100": "#84ffff",
      "rmd-cyan-a-200": "#18ffff",
      "rmd-cyan-a-400": "#00e5ff",
      "rmd-cyan-a-700": "#00b8d4",
      "rmd-teal-50": "#e0f2f1",
      "rmd-teal-100": "#b2dfdb",
      "rmd-teal-200": "#80cbc4",
      "rmd-teal-300": "#4db6ac",
      "rmd-teal-400": "#26a69a",
      "rmd-teal-500": "#009688",
      "rmd-teal-600": "#00897b",
      "rmd-teal-700": "#00796b",
      "rmd-teal-800": "#00695c",
      "rmd-teal-900": "#004d40",
      "rmd-teal-a-100": "#a7ffeb",
      "rmd-teal-a-200": "#64ffda",
      "rmd-teal-a-400": "#1de9b6",
      "rmd-teal-a-700": "#00bfa5",
      "rmd-green-50": "#e8f5e9",
      "rmd-green-100": "#c8e6c9",
      "rmd-green-200": "#a5d6a7",
      "rmd-green-300": "#81c784",
      "rmd-green-400": "#66bb6a",
      "rmd-green-500": "#4caf50",
      "rmd-green-600": "#43a047",
      "rmd-green-700": "#388e3c",
      "rmd-green-800": "#2e7d32",
      "rmd-green-900": "#1b5e20",
      "rmd-green-a-100": "#b9f6ca",
      "rmd-green-a-200": "#69f0ae",
      "rmd-green-a-400": "#00e676",
      "rmd-green-a-700": "#00c853",
      "rmd-light-green-50": "#f1f8e9",
      "rmd-light-green-100": "#dcedc8",
      "rmd-light-green-200": "#c5e1a5",
      "rmd-light-green-300": "#aed581",
      "rmd-light-green-400": "#9ccc65",
      "rmd-light-green-500": "#8bc34a",
      "rmd-light-green-600": "#7cb342",
      "rmd-light-green-700": "#689f38",
      "rmd-light-green-800": "#558b2f",
      "rmd-light-green-900": "#33691e",
      "rmd-light-green-a-100": "#ccff90",
      "rmd-light-green-a-200": "#b2ff59",
      "rmd-light-green-a-400": "#76ff03",
      "rmd-light-green-a-700": "#64dd17",
      "rmd-lime-50": "#f9fbe7",
      "rmd-lime-100": "#f0f4c3",
      "rmd-lime-200": "#e6ee9c",
      "rmd-lime-300": "#dce775",
      "rmd-lime-400": "#d4e157",
      "rmd-lime-500": "#cddc39",
      "rmd-lime-600": "#c0ca33",
      "rmd-lime-700": "#afb42b",
      "rmd-lime-800": "#9e9d24",
      "rmd-lime-900": "#827717",
      "rmd-lime-a-100": "#f4ff81",
      "rmd-lime-a-200": "#eeff41",
      "rmd-lime-a-400": "#c6ff00",
      "rmd-lime-a-700": "#aeea00",
      "rmd-yellow-50": "#fffde7",
      "rmd-yellow-100": "#fff9c4",
      "rmd-yellow-200": "#fff59d",
      "rmd-yellow-300": "#fff176",
      "rmd-yellow-400": "#ffee58",
      "rmd-yellow-500": "#ffeb3b",
      "rmd-yellow-600": "#fdd835",
      "rmd-yellow-700": "#fbc02d",
      "rmd-yellow-800": "#f9a825",
      "rmd-yellow-900": "#f57f17",
      "rmd-yellow-a-100": "#ffff8d",
      "rmd-yellow-a-200": "#ff0",
      "rmd-yellow-a-400": "#ffea00",
      "rmd-yellow-a-700": "#ffd600",
      "rmd-amber-50": "#fff8e1",
      "rmd-amber-100": "#ffecb3",
      "rmd-amber-200": "#ffe082",
      "rmd-amber-300": "#ffd54f",
      "rmd-amber-400": "#ffca28",
      "rmd-amber-500": "#ffc107",
      "rmd-amber-600": "#ffb300",
      "rmd-amber-700": "#ffa000",
      "rmd-amber-800": "#ff8f00",
      "rmd-amber-900": "#ff6f00",
      "rmd-amber-a-100": "#ffe57f",
      "rmd-amber-a-200": "#ffd740",
      "rmd-amber-a-400": "#ffc400",
      "rmd-amber-a-700": "#ffab00",
      "rmd-orange-50": "#fff3e0",
      "rmd-orange-100": "#fff0b2",
      "rmd-orange-200": "#ffcc80",
      "rmd-orange-300": "#ffb74d",
      "rmd-orange-400": "#ffa726",
      "rmd-orange-500": "#ff9800",
      "rmd-orange-600": "#fb8c00",
      "rmd-orange-700": "#f57c00",
      "rmd-orange-800": "#ef6c00",
      "rmd-orange-900": "#e65100",
      "rmd-orange-a-100": "#ffd180",
      "rmd-orange-a-200": "#ffab40",
      "rmd-orange-a-400": "#ff9100",
      "rmd-orange-a-700": "#ff6d00",
      "rmd-deep-orange-50": "#fbe9e7",
      "rmd-deep-orange-100": "#ffccbc",
      "rmd-deep-orange-200": "#ffab91",
      "rmd-deep-orange-300": "#ff8a65",
      "rmd-deep-orange-400": "#ff7043",
      "rmd-deep-orange-500": "#ff5722",
      "rmd-deep-orange-600": "#f4511e",
      "rmd-deep-orange-700": "#e64a19",
      "rmd-deep-orange-800": "#d84315",
      "rmd-deep-orange-900": "#bf360c",
      "rmd-deep-orange-a-100": "#ff9e80",
      "rmd-deep-orange-a-200": "#ff6e40",
      "rmd-deep-orange-a-400": "#ff3d00",
      "rmd-deep-orange-a-700": "#dd2c00",
      "rmd-brown-50": "#efebe9",
      "rmd-brown-100": "#d7ccc8",
      "rmd-brown-200": "#bcaaa4",
      "rmd-brown-300": "#a1887f",
      "rmd-brown-400": "#8d6e63",
      "rmd-brown-500": "#795548",
      "rmd-brown-600": "#6d4c41",
      "rmd-brown-700": "#5d4037",
      "rmd-brown-800": "#4e342e",
      "rmd-brown-900": "#3e2723",
      "rmd-grey-50": "#fafafa",
      "rmd-grey-100": "#f5f5f5",
      "rmd-grey-200": "#eee",
      "rmd-grey-300": "#e0e0e0",
      "rmd-grey-400": "#bdbdbd",
      "rmd-grey-500": "#9e9e9e",
      "rmd-grey-600": "#757575",
      "rmd-grey-700": "#616161",
      "rmd-grey-800": "#424242",
      "rmd-grey-900": "#212121",
      "rmd-blue-grey-50": "#eceff1",
      "rmd-blue-grey-100": "#cfd8dc",
      "rmd-blue-grey-200": "#b0bec5",
      "rmd-blue-grey-300": "#90a4ae",
      "rmd-blue-grey-400": "#78909c",
      "rmd-blue-grey-500": "#607d8b",
      "rmd-blue-grey-600": "#546e7a",
      "rmd-blue-grey-700": "#455a64",
      "rmd-blue-grey-800": "#37474f",
      "rmd-blue-grey-900": "#263238",
      "rmd-black-base": "#000",
      "rmd-white-base": "#fff",
    },
    "rmd-theme-primary-suffixes": [
      50, 100, 200, 300, 400, 500, 600, 700, 800, 900,
    ],
    "rmd-theme-accent-suffixes": [100, 200, 400, 700],
    "rmd-theme-colors": [
      "red",
      "pink",
      "purple",
      "deep-purple",
      "indigo",
      "blue",
      "light-blue",
      "cyan",
      "teal",
      "green",
      "light-green",
      "lime",
      "yellow",
      "amber",
      "orange",
      "deep-orange",
      "brown",
      "grey",
      "blue-grey",
    ],
    "rmd-theme-no-css-variables-fallback": true,
    "rmd-theme-define-colors-with-rgba": false,
    "rmd-theme-dark-elevation": true,
    "rmd-theme-light": true,
    "rmd-theme-primary": "#9c27b0",
    "rmd-theme-on-primary": "#fff",
    "rmd-theme-secondary": "#f50057",
    "rmd-theme-on-secondary": "#000",
    "rmd-theme-warning": "#ff6e40",
    "rmd-theme-on-warning": "#000",
    "rmd-theme-error": "#f44336",
    "rmd-theme-on-error": "#000",
    "rmd-theme-success": "#00c853",
    "rmd-theme-on-success": "#000",
    "rmd-theme-light-background": "#fafafa",
    "rmd-theme-light-surface": "#fff",
    "rmd-theme-dark-background": "#121212",
    "rmd-theme-dark-surface": "#424242",
    "rmd-theme-dark-class": ".dark-theme",
    "rmd-theme-background": "#fafafa",
    "rmd-theme-surface": "#fff",
    "rmd-theme-on-surface": "#000",
    "rmd-theme-light-primary-text-color": "#212121",
    "rmd-theme-light-secondary-text-color": "#757575",
    "rmd-theme-light-hint-text-color": "#a8a8a8",
    "rmd-theme-light-disabled-text-color": "#9e9e9e",
    "rmd-theme-light-icon-color": "#757575",
    "rmd-theme-dark-primary-text-color": "#d9d9d9",
    "rmd-theme-dark-secondary-text-color": "#b3b3b3",
    "rmd-theme-dark-hint-text-color": "gray",
    "rmd-theme-dark-disabled-text-color": "gray",
    "rmd-theme-dark-icon-color": "#b3b3b3",
    "rmd-theme-light-text-colors": {
      primary: "#212121",
      secondary: "#757575",
      hint: "#a8a8a8",
      disabled: "#9e9e9e",
      icon: "#757575",
    },
    "rmd-theme-dark-text-colors": {
      primary: "#d9d9d9",
      secondary: "#b3b3b3",
      hint: "gray",
      disabled: "gray",
      icon: "#b3b3b3",
    },
    "rmd-theme-primary-text-on-background-color": "#212121",
    "rmd-theme-secondary-text-on-background-color": "#757575",
    "rmd-theme-hint-text-on-background-color": "#a8a8a8",
    "rmd-theme-disabled-text-on-background-color": "#9e9e9e",
    "rmd-theme-icon-on-background-color": "#757575",
    "rmd-theme-primary-text-on-light-color": "#212121",
    "rmd-theme-secondary-text-on-light-color": "#757575",
    "rmd-theme-hint-text-on-light-color": "#a8a8a8",
    "rmd-theme-disabled-text-on-light-color": "#9e9e9e",
    "rmd-theme-icon-on-light-color": "#757575",
    "rmd-theme-primary-text-on-dark-color": "#d9d9d9",
    "rmd-theme-secondary-text-on-dark-color": "#b3b3b3",
    "rmd-theme-hint-text-on-dark-color": "gray",
    "rmd-theme-disabled-text-on-dark-color": "gray",
    "rmd-theme-icon-on-dark-color": "#b3b3b3",
    "rmd-theme-dark-elevation-colors": {
      "0": "#121212",
      "1": "#1f1f1f",
      "2": "#242424",
      "3": "#262626",
      "4": "#282828",
      "5": "#282828",
      "6": "#2c2c2c",
      "7": "#2c2c2c",
      "8": "#2f2f2f",
      "9": "#2f2f2f",
      "10": "#2f2f2f",
      "11": "#2f2f2f",
      "12": "#333",
      "13": "#333",
      "14": "#333",
      "15": "#333",
      "16": "#353535",
      "17": "#353535",
      "18": "#353535",
      "19": "#353535",
      "20": "#353535",
      "21": "#353535",
      "22": "#353535",
      "23": "#353535",
      "24": "#383838",
    },
    "rmd-theme-values": {
      background: "#fafafa",
      primary: "#9c27b0",
      "on-primary": "#fff",
      secondary: "#f50057",
      "on-secondary": "#000",
      surface: "#fff",
      "on-surface": "#000",
      warning: "#ff6e40",
      "on-warning": "#000",
      error: "#f44336",
      "on-error": "#000",
      success: "#00c853",
      "on-success": "#000",
      "text-primary-on-background": "#212121",
      "text-secondary-on-background": "#757575",
      "text-hint-on-background": "#a8a8a8",
      "text-disabled-on-background": "#9e9e9e",
      "text-icon-on-background": "#757575",
      "light-background": "#fafafa",
      "light-surface": "#fff",
      "dark-background": "#121212",
      "dark-surface": "#424242",
      "text-primary-on-light": "#212121",
      "text-secondary-on-light": "#757575",
      "text-hint-on-light": "#a8a8a8",
      "text-disabled-on-light": "#9e9e9e",
      "text-icon-on-light": "#757575",
      "text-primary-on-dark": "#d9d9d9",
      "text-secondary-on-dark": "#b3b3b3",
      "text-hint-on-dark": "gray",
      "text-disabled-on-dark": "gray",
      "text-icon-on-dark": "#b3b3b3",
    },
  },
  tooltip: {
    "rmd-tooltip-background-color": "#616161",
    "rmd-tooltip-color": "var(--rmd-theme-text-primary-on-dark, #d9d9d9)",
    "rmd-tooltip-max-width": "15rem",
    "rmd-tooltip-enter-duration": "0.15s",
    "rmd-tooltip-exit-duration": "0.15s",
    "rmd-tooltip-z-index": 50,
    "rmd-tooltip-font-size": "1rem",
    "rmd-tooltip-line-height": "1.5rem",
    "rmd-tooltip-min-height": "2rem",
    "rmd-tooltip-horizontal-padding": "1rem",
    "rmd-tooltip-line-wrap-vertical-padding": "0.5625rem",
    "rmd-tooltip-spacing": "1.5rem",
    "rmd-tooltip-dense-font-size": "0.625rem",
    "rmd-tooltip-dense-line-height": "0.825rem",
    "rmd-tooltip-dense-min-height": "1.375rem",
    "rmd-tooltip-dense-horizontal-padding": "0.5rem",
    "rmd-tooltip-dense-line-wrap-vertical-padding": "0.375rem",
    "rmd-tooltip-dense-spacing": "0.875rem",
    "rmd-tooltip-border-radius": "0.25rem",
    "rmd-tooltip-transition-distance": "0.5rem",
    "rmd-tooltip-position-values": ["above", "below", "left", "right"],
    "rmd-tooltip-theme-values": {
      "background-color": "#616161",
      color: "var(--rmd-theme-text-primary-on-dark, #d9d9d9)",
      "transition-distance": "0.5rem",
      "z-index": 50,
      spacing: "1.5rem",
      "min-height": "2rem",
      "max-width": "15rem",
      "font-size": "1rem",
      "line-height": "1.5rem",
      "horizontal-padding": "1rem",
      "vertical-padding": "0.5625rem",
      "dense-spacing": "0.875rem",
      "dense-min-height": "1.375rem",
      "dense-font-size": "0.625rem",
      "dense-line-height": "0.825rem",
      "dense-horizontal-padding": "0.5rem",
      "dense-vertical-padding": "0.375rem",
    },
  },
  transition: {
    "rmd-transition-sharp": "cubic-bezier(0.4, 0, 0.6, 1)",
    "rmd-transition-standard": "cubic-bezier(0.4, 0, 0.2, 1)",
    "rmd-transition-acceleration": "cubic-bezier(0.4, 0, 1, 1)",
    "rmd-transition-deceleration": "cubic-bezier(0, 0, 0.2, 1)",
    "rmd-transition-enter-duration": "0.2s",
    "rmd-transition-leave-duration": "0.15s",
    "rmd-transition-standard-time": "0.15s",
    "rmd-collapse-enter-transition-func": "deceleration",
    "rmd-collapse-leave-transition-func": "acceleration",
    "rmd-cross-fade-translate-distance": "-1rem",
    "rmd-cross-fade-transition-duration": "0.3s",
    "rmd-transition-scale-enter-duration": "0.2s",
    "rmd-transition-scale-leave-duration": "0.15s",
    "rmd-transition-scale-y-enter-duration": "0.2s",
    "rmd-transition-scale-y-leave-duration": "0.15s",
    "rmd-transitions": {
      sharp: "cubic-bezier(0.4, 0, 0.6, 1)",
      standard: "cubic-bezier(0.4, 0, 0.2, 1)",
      acceleration: "cubic-bezier(0.4, 0, 1, 1)",
      deceleration: "cubic-bezier(0, 0, 0.2, 1)",
    },
  },
  tree: {
    "rmd-tree-max-depth": 3,
    "rmd-tree-item-padding-incrementor": "1.5rem",
    "rmd-tree-item-padding-base": "4.5rem",
    "rmd-tree-item-focused-styles": [],
    "rmd-tree-item-keyboard-focused-styles": {
      "box-shadow": "inset 0 0 0 2px #2196f3",
    },
    "rmd-tree-theme-values": {
      incrementor: "1.5rem",
      "base-padding": "4.5rem",
    },
  },
  typography: {
    "rmd-typography-font-family": "Roboto, sans-serif",
    "rmd-typography-mobile-max-line-length": "17em",
    "rmd-typography-desktop-max-line-length": "40em",
    "rmd-typography-text-container-breakpoint": "37.5rem",
    "rmd-typography-base": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
    },
    "rmd-typography-thin": 100,
    "rmd-typography-light": 300,
    "rmd-typography-regular": 400,
    "rmd-typography-medium": 500,
    "rmd-typography-bold": 700,
    "rmd-typography-semi-bold": 800,
    "rmd-typography-black": 900,
    "rmd-typography-font-weights": {
      thin: 100,
      light: 300,
      regular: 400,
      medium: 500,
      bold: 700,
      "semi-bold": 800,
      black: 900,
    },
    "rmd-typography-default-font-weights": [
      "light",
      "regular",
      "medium",
      "bold",
    ],
    "rmd-typography-colors": {
      secondary: "text-secondary-on-background",
      hint: "text-hint-on-background",
      "theme-primary": "primary",
      "theme-secondary": "secondary",
      "theme-warning": "warning",
      "theme-error": "error",
    },
    "rmd-typography-alignments": ["left", "center", "right"],
    "rmd-typography-decorations": ["underline", "overline", "line-through"],
    "rmd-typography-transforms": ["capitalize", "uppercase", "lowercase"],
    "rmd-typography-font-styles": ["normal", "italic", "oblique"],
    "rmd-typography-google-font-weight-suffixes": {
      thin: "-Thin",
      light: "-Light",
      regular: "-Regular",
      medium: "-Medium",
      bold: "-Bold",
      "semi-bold": "-SemiBold",
      black: "-Black",
    },
    "rmd-typography-default-headline-1-styles": {
      "font-size": "6rem",
      "line-height": "6rem",
      "font-weight": 300,
      "letter-spacing": "-0.015625em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-headline-1-styles": [],
    "rmd-typography-default-headline-2-styles": {
      "font-size": "3.75rem",
      "line-height": "3.75rem",
      "font-weight": 300,
      "letter-spacing": "-0.0083333333em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-headline-2-styles": [],
    "rmd-typography-default-headline-3-styles": {
      "font-size": "3rem",
      "line-height": "3.125rem",
      "font-weight": 400,
      "letter-spacing": "normal",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-headline-3-styles": [],
    "rmd-typography-default-headline-4-styles": {
      "font-size": "2.125rem",
      "line-height": "2.5rem",
      "font-weight": 400,
      "letter-spacing": "0.0073529412em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-headline-4-styles": [],
    "rmd-typography-default-headline-5-styles": {
      "font-size": "1.5rem",
      "line-height": "2rem",
      "font-weight": 400,
      "letter-spacing": "normal",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-headline-5-styles": [],
    "rmd-typography-default-headline-6-styles": {
      "font-size": "1.25rem",
      "line-height": "2rem",
      "font-weight": 500,
      "letter-spacing": "0.0125em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-headline-6-styles": [],
    "rmd-typography-default-subtitle-1-styles": {
      "font-size": "1rem",
      "line-height": "1.75rem",
      "font-weight": 400,
      "letter-spacing": "0.009375em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-subtitle-1-styles": [],
    "rmd-typography-default-subtitle-2-styles": {
      "font-size": "0.875rem",
      "line-height": "1.375rem",
      "font-weight": 500,
      "letter-spacing": "0.0071428571em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-subtitle-2-styles": [],
    "rmd-typography-default-body-1-styles": {
      "font-size": "1rem",
      "line-height": "1.5rem",
      "font-weight": 400,
      "letter-spacing": "0.0357142857em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-body-1-styles": [],
    "rmd-typography-default-body-2-styles": {
      "font-size": "0.875rem",
      "line-height": "1.25rem",
      "font-weight": 400,
      "letter-spacing": "0.0178571429em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-body-2-styles": [],
    "rmd-typography-default-caption-styles": {
      "font-size": "0.75rem",
      "line-height": "1.25rem",
      "font-weight": 400,
      "letter-spacing": "0.0333333333em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "rmd-typography-caption-styles": [],
    "rmd-typography-default-button-styles": {
      "font-size": "0.875rem",
      "line-height": "2.25rem",
      "font-weight": 500,
      "letter-spacing": "0.0892857143em",
      "text-decoration": "none",
      "text-transform": "uppercase",
    },
    "rmd-typography-button-styles": [],
    "rmd-typography-default-overline-styles": {
      "font-size": "0.75rem",
      "line-height": "2rem",
      "font-weight": 500,
      "letter-spacing": "0.1666666667em",
      "text-decoration": "none",
      "text-transform": "uppercase",
    },
    "rmd-typography-overline-styles": [],
    "rmd-typography-styles": {
      "headline-1": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "6rem",
        "line-height": "6rem",
        "font-weight": 300,
        "letter-spacing": "-0.015625em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "headline-2": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "3.75rem",
        "line-height": "3.75rem",
        "font-weight": 300,
        "letter-spacing": "-0.0083333333em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "headline-3": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "3rem",
        "line-height": "3.125rem",
        "font-weight": 400,
        "letter-spacing": "normal",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "headline-4": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "2.125rem",
        "line-height": "2.5rem",
        "font-weight": 400,
        "letter-spacing": "0.0073529412em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "headline-5": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "1.5rem",
        "line-height": "2rem",
        "font-weight": 400,
        "letter-spacing": "normal",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "headline-6": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "1.25rem",
        "line-height": "2rem",
        "font-weight": 500,
        "letter-spacing": "0.0125em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "subtitle-1": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "1rem",
        "line-height": "1.75rem",
        "font-weight": 400,
        "letter-spacing": "0.009375em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "subtitle-2": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "0.875rem",
        "line-height": "1.375rem",
        "font-weight": 500,
        "letter-spacing": "0.0071428571em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "body-1": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "1rem",
        "line-height": "1.5rem",
        "font-weight": 400,
        "letter-spacing": "0.0357142857em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      "body-2": {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "0.875rem",
        "line-height": "1.25rem",
        "font-weight": 400,
        "letter-spacing": "0.0178571429em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      caption: {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "0.75rem",
        "line-height": "1.25rem",
        "font-weight": 400,
        "letter-spacing": "0.0333333333em",
        "text-decoration": "inherit",
        "text-transform": "inherit",
      },
      button: {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "0.875rem",
        "line-height": "2.25rem",
        "font-weight": 500,
        "letter-spacing": "0.0892857143em",
        "text-decoration": "none",
        "text-transform": "uppercase",
      },
      overline: {
        "font-family": "Roboto, sans-serif",
        "-moz-osx-font-smoothing": "grayscale",
        "-webkit-font-smoothing": "antialiased",
        "font-size": "0.75rem",
        "line-height": "2rem",
        "font-weight": 500,
        "letter-spacing": "0.1666666667em",
        "text-decoration": "none",
        "text-transform": "uppercase",
      },
    },
    "rmd-typography-theme-values": {
      "line-width": "40em",
      "mobile-line-width": "17em",
      "desktop-line-width": "40em",
    },
  },
  utils: {
    "rmd-utils-ios-scroll-momentum": true,
    "rmd-utils-auto-dense": false,
    "rmd-utils-enable-rtl": true,
    "rmd-utils-temporary-element-z-index": 30,
    "rmd-utils-swappable-positions": ["top", "right", "bottom", "left"],
    "rmd-utils-swappable-position-prefixes": ["border", "margin", "padding"],
    "rmd-utils-skip-validation": false,
    "rmd-utils-fix-moz-focus": true,
    "rmd-utils-phone-max-width": "47.9375em",
    "rmd-utils-tablet-min-width": "48em",
    "rmd-utils-tablet-max-width": "64em",
    "rmd-utils-desktop-min-width": "64.0625em",
    "rmd-utils-large-desktop-min-width": "80em",
    "rmd-grid-columns-var": "--rmd-grid-cols",
    "rmd-grid-gutter-var": "--rmd-grid-gutter",
    "rmd-grid-cell-margin-var": "--rmd-cell-margin",
    "rmd-grid-cell-size-var": "--rmd-cell-size",
    "rmd-grid-padding": "1rem",
    "rmd-grid-cell-margin": "1rem",
    "rmd-grid-columns": null,
    "rmd-grid-phone-columns": 4,
    "rmd-grid-tablet-columns": 8,
    "rmd-grid-desktop-columns": 12,
    "rmd-grid-large-desktop-columns": 12,
    "rmd-grid-list-padding": "0.5rem",
    "rmd-grid-list-cell-margin": "0.5rem",
    "rmd-grid-list-cell-max-size": "9.375rem",
  },
};
