/*
 * This file was generated from @react-md/dev-utils and should not be updated
 * manually.
 */

export default {
  "rmd-list-vertical-padding": "0.5rem",
  "rmd-list-dense-vertical-padding": "0.25rem",
  "rmd-list-horizontal-padding": 0,
  "rmd-list-dense-horizontal-padding": 0,
  "rmd-list-line-height": "1.5rem",
  "rmd-list-font-size": "1rem",
  "rmd-list-dense-font-size": "0.8125rem",
  "rmd-list-item-vertical-padding": "0.5rem",
  "rmd-list-item-horizontal-padding": "1rem",
  "rmd-list-item-height": "3rem",
  "rmd-list-item-dense-height": "2.5rem",
  "rmd-list-item-medium-height": "3.5rem",
  "rmd-list-item-dense-medium-height": "3rem",
  "rmd-list-item-large-height": "4rem",
  "rmd-list-item-dense-large-height": "3.5rem",
  "rmd-list-item-extra-large-height": "4.5rem",
  "rmd-list-item-dense-extra-large-height": "4rem",
  "rmd-list-item-three-line-height": "5.5rem",
  "rmd-list-item-dense-three-line-height": "5rem",
  "rmd-list-item-secondary-text-line-height": 1.42857,
  "rmd-list-item-secondary-text-three-line-max-height": "3rem",
  "rmd-list-item-dense-secondary-text-three-line-max-height": "2.25rem",
  "rmd-list-item-text-keyline": "4.5rem",
  "rmd-list-item-media-size": "3.5rem",
  "rmd-list-item-media-large-size": "6.25rem",
  "rmd-list-item-media-spacing": "1rem",
  "rmd-list-item-disabled-opacity": 0.5,
  "rmd-list-theme-values": {
    "vertical-padding": "0.5rem",
    "horizontal-padding": 0,
    "font-size": "1rem",
    "text-keyline": "4.5rem",
    "item-height": "3rem",
    "item-medium-height": "3.5rem",
    "item-large-height": "4rem",
    "item-extra-large-height": "4.5rem",
    "item-three-line-height": "5.5rem",
    "item-vertical-padding": "0.5rem",
    "item-horizontal-padding": "1rem",
    "item-secondary-three-line-height": "3rem",
    "dense-font-size": "0.8125rem",
    "dense-vertical-padding": "0.25rem",
    "dense-horizontal-padding": 0,
    "dense-item-height": "2.5rem",
    "dense-item-medium-height": "3rem",
    "dense-item-large-height": "3.5rem",
    "dense-item-extra-large-height": "4rem",
    "dense-item-three-line-height": "5rem",
    "dense-item-secondary-three-line-height": "2.25rem",
    "media-size": "3.5rem",
    "media-spacing": "1rem",
    "media-large-size": "6.25rem",
  },
};
