/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const NavigateNextIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function NavigateNextIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0V0z" fill="none" />
        <path d="m10.02 18 6-6-6-6-1.41 1.41L13.19 12l-4.58 4.59z" />
      </SVGIcon>
    );
  }
);
