// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY
import { type TableOfContentsItem } from "@/components/TableOfContents/types.js";

export const toc = [
  { id: "tooltip", depth: 1, value: "Tooltip" },
  {
    id: "simple-example",
    depth: 1,
    value: "Simple Example",
    items: [
      { id: "dense-tooltip", depth: 2, value: "Dense Tooltip" },
      { id: "long-text-tooltip", depth: 2, value: "Long Text Tooltip" },
    ],
  },
  {
    id: "tooltip-positioning",
    depth: 1,
    value: "Tooltip Positioning",
    items: [
      {
        id: "forced-tooltip-position",
        depth: 2,
        value: "Forced Tooltip Position",
      },
    ],
  },
  { id: "enabling-hover-mode", depth: 1, value: "Enabling Hover Mode" },
  {
    id: "configuring-tooltip-timeouts",
    depth: 1,
    value: "Configuring Tooltip Timeouts",
  },
  {
    id: "overflow-only-tooltip",
    depth: 1,
    value: "Overflow Only Tooltip",
    items: [
      {
        id: "custom-overflow-element",
        depth: 2,
        value: "Custom Overflow Element",
      },
    ],
  },
  {
    id: "custom-tooltip",
    depth: 1,
    value: "Custom Tooltip",
    items: [
      {
        id: "progressbar-tooltip-example",
        depth: 2,
        value: "Progressbar Tooltip Example",
      },
    ],
  },
  { id: "accessibility", depth: 1, value: "Accessibility" },
] satisfies readonly TableOfContentsItem[];
