/*
 * This file was generated from @react-md/dev-utils and should not be updated
 * manually.
 */

export default {
  "rmd-tooltip-background-color": "#616161",
  "rmd-tooltip-color": "var(--rmd-theme-text-primary-on-dark, #d9d9d9)",
  "rmd-tooltip-max-width": "15rem",
  "rmd-tooltip-enter-duration": "0.15s",
  "rmd-tooltip-exit-duration": "0.15s",
  "rmd-tooltip-z-index": 50,
  "rmd-tooltip-font-size": "1rem",
  "rmd-tooltip-line-height": "1.5rem",
  "rmd-tooltip-min-height": "2rem",
  "rmd-tooltip-horizontal-padding": "1rem",
  "rmd-tooltip-line-wrap-vertical-padding": "0.5625rem",
  "rmd-tooltip-spacing": "1.5rem",
  "rmd-tooltip-dense-font-size": "0.625rem",
  "rmd-tooltip-dense-line-height": "0.825rem",
  "rmd-tooltip-dense-min-height": "1.375rem",
  "rmd-tooltip-dense-horizontal-padding": "0.5rem",
  "rmd-tooltip-dense-line-wrap-vertical-padding": "0.375rem",
  "rmd-tooltip-dense-spacing": "0.875rem",
  "rmd-tooltip-border-radius": "0.25rem",
  "rmd-tooltip-transition-distance": "0.5rem",
  "rmd-tooltip-position-values": ["above", "below", "left", "right"],
  "rmd-tooltip-theme-values": {
    "background-color": "#616161",
    color: "var(--rmd-theme-text-primary-on-dark, #d9d9d9)",
    "transition-distance": "0.5rem",
    "z-index": 50,
    spacing: "1.5rem",
    "min-height": "2rem",
    "max-width": "15rem",
    "font-size": "1rem",
    "line-height": "1.5rem",
    "horizontal-padding": "1rem",
    "vertical-padding": "0.5625rem",
    "dense-spacing": "0.875rem",
    "dense-min-height": "1.375rem",
    "dense-font-size": "0.625rem",
    "dense-line-height": "0.825rem",
    "dense-horizontal-padding": "0.5rem",
    "dense-vertical-padding": "0.375rem",
  },
};
