/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const SkipNextIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function SkipNextIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0z" fill="none" />
        <path d="m6 18 8.5-6L6 6v12zM16 6v12h2V6h-2z" />
      </SVGIcon>
    );
  }
);
