/** this is an auto-generated file from @react-md/dev-utils */
export default {
  "rmd-app-bar-z-index": 10,
  "rmd-app-bar-fixed-elevation": 2,
  "rmd-app-bar-height": "3.5rem",
  "rmd-app-bar-dense-height": "3rem",
  "rmd-app-bar-prominent-height": "7rem",
  "rmd-app-bar-prominent-dense-height": "6rem",
  "rmd-app-bar-keyline": "1rem",
  "rmd-app-bar-nav-margin": "0.25rem",
  "rmd-app-bar-title-keyline": "4.5rem",
  "rmd-app-bar-title-nav-margin": "1.25rem",
  "rmd-app-bar-lr-margin": "0.25rem",
  "rmd-app-bar-default-background-color": "#f5f5f5",
  "rmd-app-bar-theme-values": {
    "background-color": "transparent",
    color: "initial",
    primary: "var(--rmd-theme-primary, #9c27b0)",
    "on-primary": "var(--rmd-theme-on-primary, #fff)",
    secondary: "var(--rmd-theme-secondary, #f50057)",
    "on-secondary": "var(--rmd-theme-on-secondary, #fff)",
    "default-background-color": "#f5f5f5",
    "default-light-background-color": "#f5f5f5",
    "default-dark-background-color": "#212121",
    "default-color": "#fff",
    "default-light-color": "#fff",
    "default-dark-color": "#000",
    height: "3.5rem",
    "dense-height": "3rem",
    "prominent-height": "7rem",
    "prominent-dense-height": "6rem",
  },
};
