import { lazy, ReactType } from "react";

export const slides = [
  "agenda.md",
  "what.md",
  "what1.md",
  "how.md",
  "how-vdom1.md",
  "how-vdom2.md",
  "how-updates.md",
  "how-jsx.md",
  lazy(() => import("./slides/Demo")),
  "state.md",
  "state1.md",
  "state2.md",
  "demo.md",
  "future.md",
  "future-context.md",
  "demo.md",
  "future-hooks.md",
  "demo.md",
  "future-suspense.md",
  "demo.md",
  // "future-async.md",
  "testing.md",
  "questions.md",
  lazy(() => import("./slides/Credits")),
  "links.md",
];
