/*
 * This file was generated from @react-md/dev-utils and should not be updated
 * manually.
 */

export default {
  "rmd-chip-disable-focus-background-color": true,
  "rmd-chip-height": "2rem",
  "rmd-chip-border-radius": "1rem",
  "rmd-chip-small-spacing": "0.25rem",
  "rmd-chip-medium-spacing": "0.5rem",
  "rmd-chip-large-spacing": "0.75rem",
  "rmd-chip-icon-size": "1.125rem",
  "rmd-chip-avatar-size": "1.5rem",
  "rmd-chip-progress-size": "1.125rem",
  "rmd-chip-progress-width": 12,
  "rmd-chip-themed-background-color": "#ba68c8",
  "rmd-chip-themed-color": "#fff",
  "rmd-chip-solid-light-background-color": "#e0e0e0",
  "rmd-chip-solid-light-color": "#000",
  "rmd-chip-solid-light-disabled-background-color": "#f5f5f5",
  "rmd-chip-solid-dark-background-color": "#212121",
  "rmd-chip-solid-dark-color": "#fff",
  "rmd-chip-solid-dark-disabled-background-color": "#262626",
  "rmd-chip-solid-background-color": "#e0e0e0",
  "rmd-chip-solid-color": "#000",
  "rmd-chip-solid-disabled-background-color": "#f5f5f5",
  "rmd-chip-outline-light-background-color": "#fff",
  "rmd-chip-outline-light-color": "#000",
  "rmd-chip-outline-dark-background-color": "#424242",
  "rmd-chip-outline-dark-color": "#fff",
  "rmd-chip-outline-background-color": "#fff",
  "rmd-chip-outline-color": "#000",
  "rmd-chip-outline-border-color": "#e0e0e0",
  "rmd-chip-transition-duration": "0.15s",
  "rmd-chip-box-shadow": "inset 0 0 0 1px",
  "rmd-chip-theme-values": {
    height: "2rem",
    "border-radius": "1rem",
    "themed-background-color": "#ba68c8",
    "themed-color": "#fff",
    "solid-background-color": "#e0e0e0",
    "solid-color": "#000",
    "solid-disabled": "#f5f5f5",
    "outline-background-color": "#fff",
    "outline-color": "#000",
    "outline-border-color": "#e0e0e0",
    "small-spacing": "0.25rem",
    "medium-spacing": "0.5rem",
    "large-spacing": "0.75rem",
  },
};
