/* eslint-disable global-require, max-len */
import syncComponent from 'utils/syncComponent';

export const Home = syncComponent('Home', require('components/Home'));
export const NotFound = syncComponent('NotFound', require('components/NotFound'));
export const GettingStarted = syncComponent('GettingStarted', require('components/GettingStarted'));
export const Colors = syncComponent('Colors', require('components/Customization/Colors'));
export const Themes = syncComponent('Themes', require('components/Customization/Themes'));
export const Typography = syncComponent('Typography', require('components/Customization/Typography'));
export const MediaQueries = syncComponent('MediaQueries', require('components/Customization/MediaQueries'));
export const MinimizingBundle = syncComponent('MinimizingBundle', require('components/Customization/MinimizingBundle'));
export const WhatsNew = syncComponent('WhatsNew', require('components/DiscoverMore/WhatsNew'));
export const UpgradeV030 = syncComponent('UpgradeV030', require('components/DiscoverMore/UpgradeGuides/v0.3.0'));
export const UpgradeV100 = syncComponent('UpgradeV100', require('components/DiscoverMore/UpgradeGuides/v1.0.0'));
export const UpgradeV110 = syncComponent('UpgradeV110', require('components/DiscoverMore/UpgradeGuides/v1.1.0'));
export const Showcases = syncComponent('Showcases', require('components/DiscoverMore/Showcases'));
export const Community = syncComponent('Community', require('components/DiscoverMore/Community'));
export const Contributing = syncComponent('Contributing', require('components/DiscoverMore/Contributing'));

export const SassDocPage = syncComponent('SassDocPage', require('components/SassDocPage'));
export const PropTypesPage = syncComponent('PropTypesPage', require('components/PropTypesPage'));

// components
export const Autocompletes = syncComponent('Autocompletes', require('components/Components/autocompletes'));
export const Avatars = syncComponent('Avatars', require('components/Components/avatars'));
export const Badges = syncComponent('Badges', require('components/Components/badges'));
export const BottomNavigations = syncComponent('BottomNavigations', require('components/Components/bottom-navigations'));
export const Buttons = syncComponent('Buttons', require('components/Components/buttons'));
export const Cards = syncComponent('Cards', require('components/Components/cards'));
export const Chips = syncComponent('Chips', require('components/Components/chips'));
export const DataTables = syncComponent('DataTables', require('components/Components/data-tables'));
export const Dialogs = syncComponent('Dialogs', require('components/Components/dialogs'));
export const Dividers = syncComponent('Dividers', require('components/Components/dividers'));
export const Drawers = syncComponent('Drawers', require('components/Components/drawers'));
export const ExpansionPanels = syncComponent('ExpansionPanels', require('components/Components/expansion-panels'));
export const FileInputs = syncComponent('FileInputs', require('components/Components/file-inputs'));
export const FontIcons = syncComponent('FontIcons', require('components/Components/font-icons'));
export const AccessibleFakeButtons = syncComponent('AccessibleFakeButtons', require('components/Components/helpers/accessible-fake-buttons'));
export const Collapses = syncComponent('Collapses', require('components/Components/helpers/collapses'));
export const FocusContainers = syncComponent('FocusContainers', require('components/Components/helpers/focus-containers'));
export const IconSeparators = syncComponent('IconSeparators', require('components/Components/helpers/icon-separators'));
export const Layovers = syncComponent('Layovers', require('components/Components/helpers/layovers'));
export const Portals = syncComponent('Portals', require('components/Components/helpers/portals'));
export const Inks = syncComponent('Inks', require('components/Components/inks'));
export const Lists = syncComponent('Lists', require('components/Components/lists'));
export const Media = syncComponent('Media', require('components/Components/media'));
export const Menus = syncComponent('Menus', require('components/Components/menus'));
export const NavigationDrawers = syncComponent('NavigationDrawers', require('components/Components/navigation-drawers'));
export const Papers = syncComponent('Papers', require('components/Components/papers'));
export const DatePickers = syncComponent('DatePickers', require('components/Components/pickers/date'));
export const TimePickers = syncComponent('TimePickers', require('components/Components/pickers/time'));
export const CircularProgress = syncComponent('CircularProgress', require('components/Components/progress/circular'));
export const LinearProgress = syncComponent('LinearProgress', require('components/Components/progress/linear'));
export const SelectFields = syncComponent('SelectFields', require('components/Components/select-fields'));
export const SelectionControls = syncComponent('SelectionControls', require('components/Components/selection-controls/selection-controls'));
export const Checkboxes = syncComponent('Checkboxes', require('components/Components/selection-controls/checkboxes'));
export const Radios = syncComponent('Radios', require('components/Components/selection-controls/radios'));
export const Switches = syncComponent('Switches', require('components/Components/selection-controls/switches'));
export const Sliders = syncComponent('Sliders', require('components/Components/sliders'));
export const Snackbars = syncComponent('Snackbars', require('components/Components/snackbars'));
export const Subheaders = syncComponent('Subheaders', require('components/Components/subheaders'));
export const Tabs = syncComponent('Tabs', require('components/Components/tabs'));
export const TextFields = syncComponent('TextFields', require('components/Components/text-fields'));
export const Toolbars = syncComponent('Toolbars', require('components/Components/toolbars'));
export const Tooltips = syncComponent('Tooltips', require('components/Components/tooltips'));
