/** this is an auto-generated file from @react-md/dev-utils */
export default {
  "rmd-form-error-color": "#f44336",
  "rmd-form-error-hover-color": "#ff8a80",
  "rmd-form-active-color": "var(--rmd-theme-secondary, #f50057)",
  "rmd-form-disabled-color":
    "var(--rmd-theme-text-disabled-on-background, #9e9e9e)",
  "rmd-form-placeholder-color":
    "var(--rmd-theme-text-secondary-on-background, #757575)",
  "rmd-label-font-size": "1em",
  "rmd-label-floating-font-size": "0.75em",
  "rmd-label-padding": "0.25rem",
  "rmd-label-floating-top": "1.6rem",
  "rmd-form-theme-values": {
    "error-color": "#f44336",
    "error-hover-color": "#ff8a80",
    "toggle-color": "#ff6e40",
    "active-color": "var(--rmd-theme-secondary, #f50057)",
    "disabled-color": "var(--rmd-theme-text-disabled-on-background, #9e9e9e)",
    "placeholder-color":
      "var(--rmd-theme-text-secondary-on-background, #757575)",
    "label-floating-top": "1.6rem",
    "filled-color": "#dcdcdc",
    "filled-light-color": "#616161",
    "filled-dark-color": "#616161",
    "border-color": "rgba(0, 0, 0, 0.5)",
    "border-hover-color": "rgba(0, 0, 0, 0.87)",
    "border-width": "1px",
    "border-width-active": "2px",
    "border-radius": "0.25rem",
    offset: "0px",
    "horizontal-padding": "0px",
    "vertical-padding": "0px",
    "underline-horizontal-padding": "0.75rem",
    "outline-horizontal-padding": "1rem",
    "toggle-inset": "0.3125rem",
    "toggle-dense-inset": "0.25rem",
    "track-background-color": "rgba(0, 0, 0, 0.38)",
    "textarea-min-height": "1.5em",
    "textarea-margin-top": "0px",
  },
};
