/** this is an auto-generated file from @react-md/dev-utils */
export default {
  "rmd-form-error-color": "#f44336",
  "rmd-form-error-hover-color": "#d50000",
  "rmd-form-active-color": "var(--rmd-theme-secondary, #f50057)",
  "rmd-form-disabled-color":
    "var(--rmd-theme-text-disabled-on-background, #9e9e9e)",
  "rmd-form-placeholder-color":
    "var(--rmd-theme-text-secondary-on-background, #757575)",
  "rmd-form-theme-values": {
    "error-color": "#f44336",
    "error-hover-color": "#d50000",
    "active-color": "var(--rmd-theme-secondary, #f50057)",
    "disabled-color": "var(--rmd-theme-text-disabled-on-background, #9e9e9e)",
    "toggle-inset": "0.3125rem",
    "toggle-dense-inset": "0.25rem",
    "indeterminate-height": "0.15rem",
    "indeterminate-dense-height": "0.125rem",
    "track-background-color": "rgba(0, 0, 0, 0.38)",
    "floating-top": "1rem",
    "floating-dense-top": "0.9rem",
    "addon-top": "auto",
    "addon-margin-top": "0px",
    "label-left-offset": "0px",
    "label-top-offset": "0px",
    "label-active-padding": "0px",
    "label-active-background-color": "transparent",
    "text-padding-left": "0px",
    "text-padding-right": "0px",
    "text-padding-top": "0px",
    "text-offset": "0px",
    "text-active-color": "#2196f3",
    "text-border-color": "rgba(0, 0, 0, 0.12)",
    "text-border-hover-color": "rgba(0, 0, 0, 0.87)",
    "text-filled-color": "#f5f5f5",
    "text-height": "3rem",
    "text-label-height": "3.5rem",
    "text-label-dense-height": "3.25rem",
    "text-placeholder-height": "3rem",
    "text-placeholder-dense-height": "2.5rem",
    "textarea-padding": "0.5rem",
  },
  "rmd-label-font-size": "1em",
  "rmd-label-floating-font-size": "0.75em",
  "rmd-label-floating-padding": "0.25rem",
  "rmd-label-floating-top": "1rem",
  "rmd-label-floating-dense-top": "0.9rem",
  "rmd-label-padding": "0.25rem",
  "rmd-select-native-multiple-padding": "0.75rem",
  "rmd-select-native-addon-top": "1rem",
  "rmd-listbox-z-index": 30,
  "rmd-listbox-elevation": 8,
  "rmd-option-focused-styles": { "box-shadow": "inset 0 0 0 2px #2196f3" },
  "rmd-option-selected-styles": {
    "background-color": "#0d47a1",
    color: "#fff",
  },
  "rmd-option-selected-offset": "0.5rem",
  "rmd-option-selected-content": "✓",
  "rmd-option-horizontal-padding": "1.5rem",
  "rmd-text-field-active-color": "#2196f3",
  "rmd-text-field-light-border-color": "rgba(0, 0, 0, 0.12)",
  "rmd-text-field-dark-border-color": "rgba(255, 255, 255, 0.5)",
  "rmd-text-field-border-color": "rgba(0, 0, 0, 0.12)",
  "rmd-text-field-light-border-hover-color": "rgba(0, 0, 0, 0.87)",
  "rmd-text-field-dark-border-hover-color": "rgba(255, 255, 255, 0.87)",
  "rmd-text-field-border-hover-color": "rgba(0, 0, 0, 0.87)",
  "rmd-text-field-border-radius": "0.25rem",
  "rmd-text-field-border-width": "1px",
  "rmd-text-field-border-width-active": "2px",
  "rmd-text-field-label-height": "3.5rem",
  "rmd-text-field-label-dense-height": "3.25rem",
  "rmd-text-field-height": "3rem",
  "rmd-text-field-dense-height": "2.5rem",
  "rmd-text-field-outline-padding": "1rem",
  "rmd-text-field-underline-label-padding-top": "1rem",
  "rmd-text-field-underline-label-left-offset": "0.5rem",
  "rmd-text-field-underline-dense-padding-top": "0.25rem",
  "rmd-text-field-underline-padding": "",
  "rmd-text-field-filled-padding": "0.75rem",
  "rmd-text-field-filled-light-background-color": "#f5f5f5",
  "rmd-text-field-filled-dark-background-color": "#616161",
  "rmd-text-field-filled-background-color": "#f5f5f5",
  "rmd-text-field-filled-border-radius": "0.25rem",
  "rmd-text-field-addon-margin": "0.5rem",
  "rmd-textarea-vertical-padding": "0.5rem",
  "rmd-textarea-addon-top": "1rem",
  "rmd-form-message-min-height": "2rem",
  "rmd-form-message-margin-top": "0.5rem",
  "rmd-form-message-margin-bottom": "1rem",
  "rmd-form-message-counter-spacing": "0.5rem",
  "rmd-form-message-font-size": "0.75rem",
  "rmd-toggle-border-radius": "50%",
  "rmd-toggle-inset": "0.3125rem",
  "rmd-toggle-dense-inset": "0.25rem",
  "rmd-checkbox-indeterminate-height": "0.15rem",
  "rmd-checkbox-indeterminate-dense-height": "0.125rem",
  "rmd-switch-track-height": "1rem",
  "rmd-switch-track-width": "2.25rem",
  "rmd-switch-track-background-color": "rgba(0, 0, 0, 0.38)",
  "rmd-switch-track-border-radius": "0.5rem",
  "rmd-switch-ball-size": "1.25rem",
  "rmd-switch-ball-border-radius": "50%",
  "rmd-switch-ball-offset": "0.25rem",
  "rmd-switch-container-vertical-padding": "0.5rem",
  "rmd-switch-container-horizontal-padding": "0.625rem",
  "rmd-switch-ball-disabled-color": "#f48fb1",
  "rmd-switch-progress-width": 12,
  "rmd-switch-progress-background-color": "#fff",
  "rmd-switch-progress-padding": "0.125rem",
};
