/** this is an auto-generated file from @react-md/dev-utils */
export default {
  "rmd-sheet-z-index": 5,
  "rmd-sheet-raised-z-index": 30,
  "rmd-sheet-overlay-z-index": 30,
  "rmd-sheet-elevation": 2,
  "rmd-sheet-raised-elevation": 16,
  "rmd-sheet-enter-duration": "0.2s",
  "rmd-sheet-leave-duration": "0.15s",
  "rmd-sheet-touch-margin": "3.5rem",
  "rmd-sheet-touch-width": "calc(100vw - 3.5rem)",
  "rmd-sheet-static-width": "16rem",
  "rmd-sheet-max-height": "100%",
  "rmd-sheet-touchable-max-height": "calc(100% - 3.5rem)",
  "rmd-sheet-recommended-min-height": "3.5rem",
  "rmd-sheet-recommended-max-height": "50%",
  "rmd-sheet-positions": ["top", "right", "bottom", "left"],
  "rmd-sheet-enabled-positions": ["top", "right", "bottom", "left"],
  "rmd-sheet-theme-values": {
    "touch-width": "calc(100vw - 3.5rem)",
    "static-width": "16rem",
    "touchable-max-height": "calc(100% - 3.5rem)",
    "max-height": null,
    height: null,
    width: null,
    "transform-offscreen": null,
  },
};
