export default [
  'Orlando',
  'Sydney',
  'London',
  'Paris',
  'Venice',
  'Manhattan',
  'Cape Town',
  'Las Vegas',
  'Rome',
  'Great Barrier Reef',
  'Rio De Janeiro',
  'Maldives',
  'Hawaii',
  'South Island',
  'Grand Canyon',
  'San Diego',
  'Niagara Falls',
  'San Francisco',
  'Los Angeles',
  'Dubai',
  'Auckand',
  'Singapore',
  'Seychelles',
  'Bali',
  'Durban',
  'Bangkok',
  'Iceland',
  'Whitsundays',
  'Cairns',
  'Costa Del Sol',
  'Antigua & Barbuda',
  'Melbournce',
  'Giza',
  'Mallorca',
  'Lake District',
  'Barbados',
  'Bahamas',
  'Abu Simbel',
  'Bora Bora',
  'Sharm El Sheikh',
  'New Your State',
  'Mandrid',
  'Algarve',
  'Zermatt',
  'Victoria Falls',
  'Marbella',
  'Masai Mara',
  'Chichen Itza',
  'Disney World Florida',
  'Florence',
  'Puerto Banus',
  'Toronto',
  'Agra',
  'Great Wall',
  'Edinburgh',
  'Menorca',
  'Monaco',
  'Luxor',
  'Hong Kong',
  'Banff',
  'Sorrento',
  'Key West',
  'Koh Samui',
  'Cancun',
  'Nice',
  'Machu Picchu',
  'Yosemite National Park',
  'Oahu',
  'Florida Keys',
  'Guam',
  'Dublin Region',
  'Vancouver',
  'Ayers Rock',
  'La Digue',
  'Cayman Islands',
  'Naples',
  'St Pete Beach',
  'Amritsar',
  'Barcelona',
  'Ibiza',
  'Adelaide',
  'Airlie Beach',
  'Benidorm',
  'Buenos Aires',
  'Prague',
  'Aberdare National Park',
  'Cuba',
  'Paphos',
  'Valley of the Kings',
  'Galapagos Islands',
  'Isle of Man',
  'Kusadasi',
  'Chamonix',
  'Beijing',
  'Cannes',
  'Amsterdam',
  'Bodrum',
  'Iguassu Falls',
  'Courchevel',
  'Berlin',
];
