// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY
import { type TableOfContentsItem } from "@/components/TableOfContents/types.js";

export const toc = [
  { id: "theme", depth: 1, value: "Theme" },
] satisfies readonly TableOfContentsItem[];
