// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY
import "server-only";
import { type FakeScssModule } from "../utils/fakeScssModules.js";

export const SCSS_MODULES: Record<string, FakeScssModule> = {
  "src/app/components/carousel/CarouselExample.module.scss": {
    css: ".CarouselExample_card__Q2Fyb {\n  --rmd-button-color: #fff;\n  max-width: 42rem;\n}\n\n.CarouselExample_container__Q2Fyb {\n  position: relative;\n}\n\n.CarouselExample_control__Q2Fyb {\n  border-radius: 0;\n  bottom: 0;\n  height: 100%;\n  position: absolute;\n  top: 0;\n  width: 5rem;\n}\n.CarouselExample_control__Q2Fyb:nth-of-type(2) {\n  right: 0;\n}\n\n.CarouselExample_slide__Q2Fyb {\n  --rmd-slide-duration: 0.5s;\n  height: 22.5rem;\n  overflow: hidden;\n}\n\n.CarouselExample_overlay__Q2Fyb {\n  padding-bottom: 4rem;\n}\n\n.CarouselExample_indicators__Q2Fyb {\n  align-items: center;\n  bottom: 0;\n  display: flex;\n  gap: 0.25rem;\n  justify-content: center;\n  left: 0;\n  padding: 1rem;\n  padding-bottom: 0.25rem;\n  position: absolute;\n  right: 0;\n}\n\n.CarouselExample_tablist__Q2Fyb {\n  gap: 0.25rem;\n  width: auto;\n}\n\n.CarouselExample_indicator__Q2Fyb {\n  background-color: rgba(255, 255, 255, 0.54);\n  height: 0.75rem;\n  min-width: 3rem;\n  width: 3rem;\n}\n.CarouselExample_indicator__Q2Fyb[aria-selected=true] {\n  background-color: #fff;\n}",
    scss: '@use "everything";\n\n.card {\n  @include everything.button-set-var(color, everything.$white);\n\n  max-width: 42rem;\n}\n\n.container {\n  position: relative;\n}\n\n.control {\n  border-radius: 0;\n  bottom: 0;\n  height: 100%;\n  position: absolute;\n  top: 0;\n  width: 5rem;\n\n  &:nth-of-type(2) {\n    right: 0;\n  }\n}\n\n.slide {\n  @include everything.transition-set-var(slide-duration, 0.5s);\n\n  height: 22.5rem;\n  overflow: hidden;\n}\n\n.overlay {\n  padding-bottom: 4rem;\n}\n\n.indicators {\n  align-items: center;\n  bottom: 0;\n  display: flex;\n  gap: 0.25rem;\n  justify-content: center;\n  left: 0;\n  padding: 1rem;\n  padding-bottom: 0.25rem;\n  position: absolute;\n  right: 0;\n}\n\n.tablist {\n  gap: 0.25rem;\n  width: auto;\n}\n\n.indicator {\n  background-color: rgba(everything.$white, 0.54);\n  height: 0.75rem;\n  min-width: 3rem;\n  width: 3rem;\n\n  &[aria-selected="true"] {\n    background-color: everything.$white;\n  }\n}\n',
    baseName: "CarouselExample",
    fileName: "CarouselExample.module.scss",
  },
  "src/app/components/dialog/CustomTransitionExample.module.scss": {
    css: ".CustomTransitionExample_enter__Q3Vzd {\n  opacity: 0;\n}\n\n.CustomTransitionExample_enterActive__Q3Vzd {\n  opacity: 1;\n  transition: opacity 0.2s cubic-bezier(0, 0, 0.2, 1);\n}\n\n.CustomTransitionExample_exit__Q3Vzd {\n  opacity: 1;\n}\n\n.CustomTransitionExample_exitActive__Q3Vzd {\n  opacity: 0;\n  transition: opacity 0.2s cubic-bezier(0.4, 0, 1, 1);\n}\n\n.CustomTransitionExample_dialog__Q3Vzd {\n  width: 30rem;\n}",
    scss: '@use "everything";\n\n.enter {\n  opacity: 0;\n}\n\n.enterActive {\n  opacity: 1;\n  transition: opacity everything.$enter-duration\n    everything.$deceleration-timing-function;\n}\n\n.exit {\n  opacity: 1;\n}\n\n.exitActive {\n  opacity: 0;\n  transition: opacity everything.$enter-duration\n    everything.$acceleration-timing-function;\n}\n\n.dialog {\n  width: 30rem;\n}\n',
    baseName: "CustomTransitionExample",
    fileName: "CustomTransitionExample.module.scss",
  },
  "src/app/components/table/ContainerBasedStickyTableExample.module.scss": {
    css: ".ContainerBasedStickyTableExample_container__Q29ud {\n  margin: 0 4rem;\n  max-height: 20rem;\n  width: 100%;\n}",
    scss: ".container {\n  margin: 0 4rem;\n  max-height: 20rem;\n  width: 100%;\n}\n",
    baseName: "ContainerBasedStickyTableExample",
    fileName: "ContainerBasedStickyTableExample.module.scss",
  },
  "src/app/components/table/StickyColumnsExample.module.scss": {
    css: ".StickyColumnsExample_container__U3RpY {\n  max-height: 25rem;\n}\n\n.StickyColumnsExample_sticky__U3RpY {\n  --rmd-table-sticky-cell: 4rem;\n}",
    scss: '@use "everything";\n\n.container {\n  max-height: 25rem;\n}\n\n.sticky {\n  // if you don\'t need auto-RTL support, you could just set the `left` value\n  // instead of using the mixin and updating the css variable\n  // @include everything.table-set-var(sticky-cell, 4rem);\n  @include everything.table-set-var(\n    sticky-cell,\n    calc(\n      everything.$table-cell-input-toggle-horizontal-padding * 2 +\n        everything.$form-input-toggle-normal-size * 2\n    )\n  );\n}\n',
    baseName: "StickyColumnsExample",
    fileName: "StickyColumnsExample.module.scss",
  },
  "src/app/components/table/UpdatingSelectedRowColorExample.module.scss": {
    css: ".UpdatingSelectedRowColorExample_selected__VXBkY {\n  --rmd-table-cell-color: currentcolor;\n}\n .mouse-mode  .UpdatingSelectedRowColorExample_selected__VXBkY:hover {\n  background-color: color-mix(in srgb, var(--rmd-primary-color, #009688) 80%, var(--rmd-on-primary-color, #000));\n}",
    scss: '@use "everything";\n\n.selected {\n  @include everything.mouse-only(true) {\n    &:hover {\n      background-color: color-mix(\n        in srgb,\n        everything.theme-get-var(primary-color) 80%,\n        everything.theme-get-var(on-primary-color)\n      );\n    }\n  }\n\n  @include everything.table-set-var(cell-color, currentcolor);\n}\n',
    baseName: "UpdatingSelectedRowColorExample",
    fileName: "UpdatingSelectedRowColorExample.module.scss",
  },
  "src/app/components/table/ViewportBasedStickyTableExample.module.scss": {
    css: ".ViewportBasedStickyTableExample_container__Vmlld {\n  --rmd-table-sticky-header: var(--rmd-layout-header-height, 3.5rem);\n}",
    scss: '@use "everything";\n\n.container {\n  @include everything.table-set-var(\n    sticky-header,\n    everything.layout-get-var(header-height)\n  );\n}\n',
    baseName: "ViewportBasedStickyTableExample",
    fileName: "ViewportBasedStickyTableExample.module.scss",
  },
};
