// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY
import "server-only";
import { type FakeScssModule } from "../utils/fakeScssModules.js";

export const SCSS_MODULES: Record<string, FakeScssModule> = {
  "src/app/components/icon-rotator/CustomRotationExample.module.scss": {
    css: ".CustomRotationExample_container__Q3Vzd {\n  --rmd-icon-rotate-from: 33deg;\n  --rmd-icon-rotate-to: 103deg;\n}",
    scss: '@use "everything";\n\n.container {\n  @include everything.icon-set-var(rotate-from, 33deg);\n  @include everything.icon-set-var(rotate-to, 103deg);\n}\n',
    baseName: "CustomRotationExample",
    fileName: "CustomRotationExample.module.scss",
  },
};
