/** this is an auto-generated file */
export default [
  { name: "rmd-button-text-icon-inherit-color", value: true },
  { name: "rmd-button-text-border-radius", value: "0.5rem" },
  { name: "rmd-button-text-horizontal-padding", value: "1rem" },
  { name: "rmd-button-text-vertical-padding", value: "0" },
  { name: "rmd-button-text-height", value: "2.25rem" },
  { name: "rmd-button-text-min-width", value: "4rem" },
  { name: "rmd-button-text-icon-size", value: "1.125rem" },
  { name: "rmd-button-icon-border-radius", value: "50%" },
  { name: "rmd-button-icon-size", value: "3rem" },
  { name: "rmd-button-hover-background-color", value: "rgba(0, 0, 0, 0.2)" },
  { name: "rmd-button-background-color-transition-time", value: "0.15s" },
  { name: "rmd-button-box-shadow-width", value: "1px" },
  { name: "rmd-button-box-shadow", value: "inset 0 0 0 1px" },
  { name: "rmd-button-outline-color", value: "#999" },
  { name: "rmd-button-background-color", value: "transparent" },
  {
    name: "rmd-button-color",
    value: "var(--rmd-theme-text-primary-on-background, #212121)",
  },
  { name: "rmd-button-contained-elevation-transition-time", value: "0.15s" },
  { name: "rmd-button-contained-resting-elevation", value: "2" },
  { name: "rmd-button-contained-pressed-elevation", value: "8" },
  {
    name: "rmd-button-theme-values",
    value: [
      { name: "text-border-radius", value: "0.5rem" },
      { name: "text-horizontal-padding", value: "1rem" },
      { name: "text-vertical-padding", value: "0" },
      { name: "text-height", value: "2.25rem" },
      { name: "text-min-width", value: "4rem" },
      { name: "icon-border-radius", value: "50%" },
      { name: "icon-size", value: "3rem" },
      { name: "resting-elevation", value: "2" },
      { name: "pressed-elevation", value: "8" },
      { name: "background-color", value: "transparent" },
      { name: "color", value: "var(--rmd-theme-text-primary-on-background" },
      { name: "#212121), outline", value: "#999" },
    ],
  },
];
