/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const LabelIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function LabelIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0V0z" fill="none" />
        <path d="M17.03 5 3 5.01v13.98l14.03.01L22 12l-4.97-7z" />
      </SVGIcon>
    );
  }
);
