/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const MarkunreadMailboxIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function MarkunreadMailboxIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0z" fill="none" />
        <path d="M22 6H10v6H8V4h6V0H6v6H2v16h20V6z" />
      </SVGIcon>
    );
  }
);
