/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const ViewAgendaIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function ViewAgendaIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0V0z" fill="none" />
        <path d="M21 13H2v8h19v-8zm0-10H2v8h19V3z" />
      </SVGIcon>
    );
  }
);
