/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const CropPortraitIcon = forwardRef<SVGSVGElement, SVGIconProps>(
  function CropPortraitIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0V0z" fill="none" />
        <path d="M19 3H5v18h14V3zm-2 16H7V5h10v14z" />
      </SVGIcon>
    );
  }
);
