/** THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY */
import { forwardRef } from "react";
import type { SVGIconProps } from "@react-md/icon";
import { SVGIcon } from "@react-md/icon";

export const Crop54Icon = forwardRef<SVGSVGElement, SVGIconProps>(
  function Crop54Icon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M0 0h24v24H0V0z" fill="none" />
        <path d="M21 5H3v14h18V5zm-2 12H5V7h14v10z" />
      </SVGIcon>
    );
  }
);
