// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { useHtmlClassName } from "@react-md/core";
import styles from "./OneDark.module.scss";

export default function OneDark(): null {
  useHtmlClassName(styles.container);

  return null;
}
