/*
 * This file was generated from @react-md/dev-utils and should not be updated
 * manually.
 */

export default {
  "rmd-typography-font-family": "Roboto, sans-serif",
  "rmd-typography-mobile-max-line-length": "17em",
  "rmd-typography-desktop-max-line-length": "40em",
  "rmd-typography-text-container-breakpoint": "37.5rem",
  "rmd-typography-base": {
    "font-family": "Roboto, sans-serif",
    "-moz-osx-font-smoothing": "grayscale",
    "-webkit-font-smoothing": "antialiased",
  },
  "rmd-typography-thin": 100,
  "rmd-typography-light": 300,
  "rmd-typography-regular": 400,
  "rmd-typography-medium": 500,
  "rmd-typography-bold": 700,
  "rmd-typography-semi-bold": 800,
  "rmd-typography-black": 900,
  "rmd-typography-font-weights": {
    thin: 100,
    light: 300,
    regular: 400,
    medium: 500,
    bold: 700,
    "semi-bold": 800,
    black: 900,
  },
  "rmd-typography-default-font-weights": ["light", "regular", "medium", "bold"],
  "rmd-typography-colors": {
    secondary: "text-secondary-on-background",
    hint: "text-hint-on-background",
    "theme-primary": "primary",
    "theme-secondary": "secondary",
    "theme-warning": "warning",
    "theme-error": "error",
  },
  "rmd-typography-alignments": ["left", "center", "right"],
  "rmd-typography-decorations": ["underline", "overline", "line-through"],
  "rmd-typography-transforms": ["capitalize", "uppercase", "lowercase"],
  "rmd-typography-font-styles": ["normal", "italic", "oblique"],
  "rmd-typography-google-font-weight-suffixes": {
    thin: '"-Thin"',
    light: '"-Light"',
    regular: '"-Regular"',
    medium: '"-Medium"',
    bold: '"-Bold"',
    "semi-bold": '"-SemiBold"',
    black: '"-Black"',
  },
  "rmd-typography-styles": {
    "headline-1": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "6rem",
      "line-height": "6rem",
      "font-weight": 300,
      "letter-spacing": "-0.01562em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-2": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "3.75rem",
      "line-height": "3.75rem",
      "font-weight": 300,
      "letter-spacing": "-0.00833em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-3": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "3rem",
      "line-height": "3.125rem",
      "font-weight": 400,
      "letter-spacing": "normal",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-4": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "2.125rem",
      "line-height": "2.5rem",
      "font-weight": 400,
      "letter-spacing": "0.00735em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-5": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "1.5rem",
      "line-height": "2rem",
      "font-weight": 400,
      "letter-spacing": "normal",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-6": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "1.25rem",
      "line-height": "2rem",
      "font-weight": 500,
      "letter-spacing": "0.0125em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "subtitle-1": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "1rem",
      "line-height": "1.75rem",
      "font-weight": 400,
      "letter-spacing": "0.00937em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "subtitle-2": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.875rem",
      "line-height": "1.375rem",
      "font-weight": 500,
      "letter-spacing": "0.00714em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "body-1": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "1rem",
      "line-height": "1.5rem",
      "font-weight": 400,
      "letter-spacing": "0.03571em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "body-2": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.875rem",
      "line-height": "1.25rem",
      "font-weight": 400,
      "letter-spacing": "0.01786em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    caption: {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.75rem",
      "line-height": "1.25rem",
      "font-weight": 400,
      "letter-spacing": "0.03333em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    button: {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.875rem",
      "line-height": "2.25rem",
      "font-weight": 500,
      "letter-spacing": "0.08929em",
      "text-decoration": "none",
      "text-transform": "uppercase",
    },
    overline: {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.75rem",
      "line-height": "2rem",
      "font-weight": 500,
      "letter-spacing": "0.16667em",
      "text-decoration": "none",
      "text-transform": "uppercase",
    },
  },
  "rmd-typography-theme-values": {
    "line-width": "40em",
    "mobile-line-width": "17em",
    "desktop-line-width": "40em",
  },
};
