/*
 * This file was generated from @react-md/dev-utils and should not be updated
 * manually.
 */

export default {
  "rmd-typography-font-family": "Roboto, sans-serif",
  "rmd-typography-mobile-max-line-length": "17em",
  "rmd-typography-desktop-max-line-length": "40em",
  "rmd-typography-text-container-breakpoint": "37.5rem",
  "rmd-typography-base": {
    "font-family": "Roboto, sans-serif",
    "-moz-osx-font-smoothing": "grayscale",
    "-webkit-font-smoothing": "antialiased",
  },
  "rmd-typography-thin": 100,
  "rmd-typography-light": 300,
  "rmd-typography-regular": 400,
  "rmd-typography-medium": 500,
  "rmd-typography-bold": 700,
  "rmd-typography-semi-bold": 800,
  "rmd-typography-black": 900,
  "rmd-typography-font-weights": {
    thin: 100,
    light: 300,
    regular: 400,
    medium: 500,
    bold: 700,
    "semi-bold": 800,
    black: 900,
  },
  "rmd-typography-default-font-weights": ["light", "regular", "medium", "bold"],
  "rmd-typography-colors": {
    secondary: "text-secondary-on-background",
    hint: "text-hint-on-background",
    "theme-primary": "primary",
    "theme-secondary": "secondary",
    "theme-warning": "warning",
    "theme-error": "error",
  },
  "rmd-typography-alignments": ["left", "center", "right"],
  "rmd-typography-decorations": ["underline", "overline", "line-through"],
  "rmd-typography-transforms": ["capitalize", "uppercase", "lowercase"],
  "rmd-typography-font-styles": ["normal", "italic", "oblique"],
  "rmd-typography-google-font-weight-suffixes": {
    thin: "-Thin",
    light: "-Light",
    regular: "-Regular",
    medium: "-Medium",
    bold: "-Bold",
    "semi-bold": "-SemiBold",
    black: "-Black",
  },
  "rmd-typography-default-headline-1-styles": {
    "font-size": "6rem",
    "line-height": "6rem",
    "font-weight": 300,
    "letter-spacing": "-0.015625em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-headline-1-styles": [],
  "rmd-typography-default-headline-2-styles": {
    "font-size": "3.75rem",
    "line-height": "3.75rem",
    "font-weight": 300,
    "letter-spacing": "-0.0083333333em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-headline-2-styles": [],
  "rmd-typography-default-headline-3-styles": {
    "font-size": "3rem",
    "line-height": "3.125rem",
    "font-weight": 400,
    "letter-spacing": "normal",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-headline-3-styles": [],
  "rmd-typography-default-headline-4-styles": {
    "font-size": "2.125rem",
    "line-height": "2.5rem",
    "font-weight": 400,
    "letter-spacing": "0.0073529412em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-headline-4-styles": [],
  "rmd-typography-default-headline-5-styles": {
    "font-size": "1.5rem",
    "line-height": "2rem",
    "font-weight": 400,
    "letter-spacing": "normal",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-headline-5-styles": [],
  "rmd-typography-default-headline-6-styles": {
    "font-size": "1.25rem",
    "line-height": "2rem",
    "font-weight": 500,
    "letter-spacing": "0.0125em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-headline-6-styles": [],
  "rmd-typography-default-subtitle-1-styles": {
    "font-size": "1rem",
    "line-height": "1.75rem",
    "font-weight": 400,
    "letter-spacing": "0.009375em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-subtitle-1-styles": [],
  "rmd-typography-default-subtitle-2-styles": {
    "font-size": "0.875rem",
    "line-height": "1.375rem",
    "font-weight": 500,
    "letter-spacing": "0.0071428571em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-subtitle-2-styles": [],
  "rmd-typography-default-body-1-styles": {
    "font-size": "1rem",
    "line-height": "1.5rem",
    "font-weight": 400,
    "letter-spacing": "0.0357142857em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-body-1-styles": [],
  "rmd-typography-default-body-2-styles": {
    "font-size": "0.875rem",
    "line-height": "1.25rem",
    "font-weight": 400,
    "letter-spacing": "0.0178571429em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-body-2-styles": [],
  "rmd-typography-default-caption-styles": {
    "font-size": "0.75rem",
    "line-height": "1.25rem",
    "font-weight": 400,
    "letter-spacing": "0.0333333333em",
    "text-decoration": "inherit",
    "text-transform": "inherit",
  },
  "rmd-typography-caption-styles": [],
  "rmd-typography-default-button-styles": {
    "font-size": "0.875rem",
    "line-height": "2.25rem",
    "font-weight": 500,
    "letter-spacing": "0.0892857143em",
    "text-decoration": "none",
    "text-transform": "uppercase",
  },
  "rmd-typography-button-styles": [],
  "rmd-typography-default-overline-styles": {
    "font-size": "0.75rem",
    "line-height": "2rem",
    "font-weight": 500,
    "letter-spacing": "0.1666666667em",
    "text-decoration": "none",
    "text-transform": "uppercase",
  },
  "rmd-typography-overline-styles": [],
  "rmd-typography-styles": {
    "headline-1": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "6rem",
      "line-height": "6rem",
      "font-weight": 300,
      "letter-spacing": "-0.015625em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-2": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "3.75rem",
      "line-height": "3.75rem",
      "font-weight": 300,
      "letter-spacing": "-0.0083333333em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-3": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "3rem",
      "line-height": "3.125rem",
      "font-weight": 400,
      "letter-spacing": "normal",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-4": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "2.125rem",
      "line-height": "2.5rem",
      "font-weight": 400,
      "letter-spacing": "0.0073529412em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-5": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "1.5rem",
      "line-height": "2rem",
      "font-weight": 400,
      "letter-spacing": "normal",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "headline-6": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "1.25rem",
      "line-height": "2rem",
      "font-weight": 500,
      "letter-spacing": "0.0125em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "subtitle-1": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "1rem",
      "line-height": "1.75rem",
      "font-weight": 400,
      "letter-spacing": "0.009375em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "subtitle-2": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.875rem",
      "line-height": "1.375rem",
      "font-weight": 500,
      "letter-spacing": "0.0071428571em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "body-1": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "1rem",
      "line-height": "1.5rem",
      "font-weight": 400,
      "letter-spacing": "0.0357142857em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    "body-2": {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.875rem",
      "line-height": "1.25rem",
      "font-weight": 400,
      "letter-spacing": "0.0178571429em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    caption: {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.75rem",
      "line-height": "1.25rem",
      "font-weight": 400,
      "letter-spacing": "0.0333333333em",
      "text-decoration": "inherit",
      "text-transform": "inherit",
    },
    button: {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.875rem",
      "line-height": "2.25rem",
      "font-weight": 500,
      "letter-spacing": "0.0892857143em",
      "text-decoration": "none",
      "text-transform": "uppercase",
    },
    overline: {
      "font-family": "Roboto, sans-serif",
      "-moz-osx-font-smoothing": "grayscale",
      "-webkit-font-smoothing": "antialiased",
      "font-size": "0.75rem",
      "line-height": "2rem",
      "font-weight": 500,
      "letter-spacing": "0.1666666667em",
      "text-decoration": "none",
      "text-transform": "uppercase",
    },
  },
  "rmd-typography-theme-values": {
    "line-width": "40em",
    "mobile-line-width": "17em",
    "desktop-line-width": "40em",
  },
};
