/** this is an auto-generated file from @react-md/dev-utils */
export default [
  { name: "rmd-typography-font-family", value: "Roboto, sans-serif" },
  { name: "rmd-typography-mobile-max-line-length", value: "17em" },
  { name: "rmd-typography-desktop-max-line-length", value: "40em" },
  { name: "rmd-typography-text-container-breakpoint", value: "600px" },
  {
    name: "rmd-typography-base",
    value: [
      { name: "font-family", value: "Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
    ],
  },
  {
    name: "rmd-typography-font-weights",
    value: [
      { name: "thin", value: "100" },
      { name: "light", value: "300" },
      { name: "regular", value: "400" },
      { name: "medium", value: "500" },
      { name: "bold", value: "700" },
      { name: "semi-bold", value: "800" },
      { name: "black", value: "900" },
    ],
  },
  {
    name: "rmd-typography-default-font-weights",
    value: "light regular medium bold",
  },
  {
    name: "rmd-typography-google-font-weight-suffixes",
    value: [
      { name: "thin", value: '"-Thin"' },
      { name: "light", value: '"-Light"' },
      { name: "regular", value: '"-Regular"' },
      { name: "medium", value: '"-Medium"' },
      { name: "bold", value: '"-Bold"' },
      { name: "semi-bold", value: '"-SemiBold"' },
      { name: "black", value: '"-Black"' },
    ],
  },
  {
    name: "rmd-typography-styles",
    value: [
      { name: "headline-1", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "6rem" },
      { name: "line-height", value: "6rem" },
      { name: "font-weight", value: "300" },
      { name: "letter-spacing", value: "-0.01562em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "headline-2", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "3.75rem" },
      { name: "line-height", value: "3.75rem" },
      { name: "font-weight", value: "300" },
      { name: "letter-spacing", value: "-0.00833em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "headline-3", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "3rem" },
      { name: "line-height", value: "3.125rem" },
      { name: "font-weight", value: "400" },
      { name: "letter-spacing", value: "normal" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "headline-4", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "2.125rem" },
      { name: "line-height", value: "2.5rem" },
      { name: "font-weight", value: "400" },
      { name: "letter-spacing", value: "0.00735em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "headline-5", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "1.5rem" },
      { name: "line-height", value: "2rem" },
      { name: "font-weight", value: "400" },
      { name: "letter-spacing", value: "normal" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "headline-6", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "1.25rem" },
      { name: "line-height", value: "2rem" },
      { name: "font-weight", value: "500" },
      { name: "letter-spacing", value: "0.0125em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "subtitle-1", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "1rem" },
      { name: "line-height", value: "1.75rem" },
      { name: "font-weight", value: "400" },
      { name: "letter-spacing", value: "0.00937em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "subtitle-2", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "0.875rem" },
      { name: "line-height", value: "1.375rem" },
      { name: "font-weight", value: "500" },
      { name: "letter-spacing", value: "0.00714em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "body-1", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "1rem" },
      { name: "line-height", value: "1.5rem" },
      { name: "font-weight", value: "400" },
      { name: "letter-spacing", value: "0.03571em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "body-2", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "0.875rem" },
      { name: "line-height", value: "1.25rem" },
      { name: "font-weight", value: "400" },
      { name: "letter-spacing", value: "0.01786em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "caption", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "0.75rem" },
      { name: "line-height", value: "1.25rem" },
      { name: "font-weight", value: "400" },
      { name: "letter-spacing", value: "0.03333em" },
      { name: "text-decoration", value: "inherit" },
      { name: "text-transform", value: "inherit)" },
      { name: "button", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "0.875rem" },
      { name: "line-height", value: "2.25rem" },
      { name: "font-weight", value: "500" },
      { name: "letter-spacing", value: "0.08929em" },
      { name: "text-decoration", value: "none" },
      { name: "text-transform", value: "uppercase)" },
      { name: "overline", value: "(font-family: Roboto" },
      { name: "sans-serif, -moz-osx-font-smoothing", value: "grayscale" },
      { name: "-webkit-font-smoothing", value: "antialiased" },
      { name: "font-size", value: "0.75rem" },
      { name: "line-height", value: "2rem" },
      { name: "font-weight", value: "500" },
      { name: "letter-spacing", value: "0.16667em" },
      { name: "text-decoration", value: "none" },
      { name: "text-transform", value: "uppercase)" },
    ],
  },
];
