// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { type SVGIconProps } from "@react-md/core/SVGIcon";
import { SVGIcon } from "@react-md/core/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function BookmarkBorderRoundedIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M17 3H7c-1.1 0-2 .9-2 2v16l7-3 7 3V5c0-1.1-.9-2-2-2m0 15-5-2.18L7 18V6c0-.55.45-1 1-1h8c.55 0 1 .45 1 1z" />
      </SVGIcon>
    );
  }
);
