// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";
import { type ReactElement } from "react";

export default function DeblurSharpIcon(props: SVGIconProps): ReactElement {
  const { ref, ...remaining } = props;

  return (
    <SVGIcon {...remaining} ref={ref}>
      <path d="M12 3v18a9 9 0 0 0 0-18" />
      <circle cx="6" cy="14" r="1" />
      <circle cx="6" cy="18" r="1" />
      <circle cx="6" cy="10" r="1" />
      <circle cx="3" cy="10" r=".5" />
      <circle cx="6" cy="6" r="1" />
      <circle cx="3" cy="14" r=".5" />
      <circle cx="10" cy="21" r=".5" />
      <circle cx="10" cy="3" r=".5" />
      <circle cx="10" cy="6" r="1" />
      <circle cx="10" cy="14" r="1.5" />
      <circle cx="10" cy="10" r="1.5" />
      <circle cx="10" cy="18" r="1" />
    </SVGIcon>
  );
}
