// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";
import { type ReactElement } from "react";

export default function DirectionsCarFilledSharpIcon(
  props: SVGIconProps
): ReactElement {
  const { ref, ...remaining } = props;

  return (
    <SVGIcon {...remaining} ref={ref}>
      <path d="M18.57 5H5.43L3 12v9h3v-2h12v2h3v-9zM7.5 16c-.83 0-1.5-.67-1.5-1.5S6.67 13 7.5 13s1.5.67 1.5 1.5S8.33 16 7.5 16m9 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5M5.81 10l1.04-3h10.29l1.04 3z" />
    </SVGIcon>
  );
}
