// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function FastForwardIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="m4 18 8.5-6L4 6zm9-12v12l8.5-6z" />
      </SVGIcon>
    );
  }
);
