// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { type SVGIconProps } from "@react-md/core/SVGIcon";
import { SVGIcon } from "@react-md/core/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function FileDownloadIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M19 9h-4V3H9v6H5l7 7zM5 18v2h14v-2z" />
      </SVGIcon>
    );
  }
);
