// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";
import { type ReactElement } from "react";

export default function KeyboardDoubleArrowUpTwoToneIcon(
  props: SVGIconProps
): ReactElement {
  const { ref, ...remaining } = props;

  return (
    <SVGIcon {...remaining} ref={ref}>
      <path d="M6 17.59 7.41 19 12 14.42 16.59 19 18 17.59l-6-6z" />
      <path d="m6 11 1.41 1.41L12 7.83l4.59 4.58L18 11l-6-6z" />
    </SVGIcon>
  );
}
