// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function LinkedCameraTwoToneIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M20 20H4V8h4.05l1.83-2H15V4H9L7.17 6H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V9h-2zM16 2v1.33c2.58 0 4.66 2.09 4.67 4.66H22A6.003 6.003 0 0 0 16 2m0 2.67V6c1.11 0 1.99.89 2 1.99h1.33A3.327 3.327 0 0 0 16 4.67" />
        <path
          d="M14.98 10.01c-.13-.09-.26-.18-.39-.26.14.08.27.17.39.26M17 9a2.02 2.02 0 0 0-1.01-1.73C15.7 7.1 15.36 7 15 7V6H9.88L8.05 8H4v12h16V9zm-5 10c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5"
          opacity=".3"
        />
        <path d="M12 9c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5m0 8c-1.65 0-3-1.35-3-3s1.35-3 3-3 3 1.35 3 3-1.35 3-3 3" />
      </SVGIcon>
    );
  }
);
