// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { type SVGIconProps } from "@react-md/core/SVGIcon";
import { SVGIcon } from "@react-md/core/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function MediaBluetoothOffRoundedIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M9 6.17V5c0-1.1.9-2 2-2h2c1.1 0 2 .9 2 2s-.9 2-2 2h-2v1.17zM19.42 15l2.18 2.17c.22.22.22.58 0 .8s-.58.22-.8 0l-5.98-5.98a.567.567 0 0 1 0-.8c.22-.22.58-.22.8 0l2.35 2.35V9.61c0-.45.54-.67.85-.35l2.82 2.82c.2.2.2.51 0 .71zm-.25-1.45 1.13-1.13-1.13-1.13zm1.32 6.94a.996.996 0 1 1-1.41 1.41l-3.28-3.28-.16.16a.61.61 0 0 1-.85 0 .61.61 0 0 1 0-.85l.16-.16L11 13.83v3.02c0 2.07-1.68 4.01-3.74 4.14C4.94 21.13 3 19.29 3 17c0-2.21 1.79-4 4.01-4 .73 0 1.41.21 2 .55v-1.72L2.1 4.92a.996.996 0 1 1 1.41-1.41z" />
      </SVGIcon>
    );
  }
);
