// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";
import { type ReactElement } from "react";

export default function MoveToInboxRoundedIcon(
  props: SVGIconProps
): ReactElement {
  const { ref, ...remaining } = props;

  return (
    <SVGIcon {...remaining} ref={ref}>
      <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2m0 11h-3.56c-.36 0-.68.19-.86.5-.52.9-1.47 1.5-2.58 1.5s-2.06-.6-2.58-1.5a1 1 0 0 0-.86-.5H5V5h14zm-4.21-4H13V7c0-.55-.45-1-1-1s-1 .45-1 1v3H9.21c-.45 0-.67.54-.35.85l2.79 2.79c.2.2.51.2.71 0l2.79-2.79a.5.5 0 0 0-.36-.85" />
    </SVGIcon>
  );
}
