// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { type SVGIconProps } from "@react-md/core/SVGIcon";
import { SVGIcon } from "@react-md/core/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function NetworkWifi1BarSharpIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M12 4C7.31 4 3.07 5.9 0 8.98L12 21 24 8.98A16.88 16.88 0 0 0 12 4m3.32 10.84C14.34 14.3 13.2 14 12 14s-2.34.3-3.32.84L2.92 9.07C5.51 7.08 8.67 6 12 6s6.49 1.08 9.08 3.07z" />
      </SVGIcon>
    );
  }
);
