// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function NetworkCellIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M2 22h20V2zm18-2h-3V9.83l3-3z" />
      </SVGIcon>
    );
  }
);
