// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";
import { type ReactElement } from "react";

export default function NoMeetingRoomSharpIcon(
  props: SVGIconProps
): ReactElement {
  const { ref, ...remaining } = props;

  return (
    <SVGIcon {...remaining} ref={ref}>
      <path d="M14 6h3v7.88l2 2V4h-5V3H6.12L14 10.88zm-2 5.71V13h-2v-2h1.29L2.41 2.13 1 3.54l4 4V19H3v2h11v-4.46L20.46 23l1.41-1.41z" />
    </SVGIcon>
  );
}
