// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { type SVGIconProps } from "@react-md/core/SVGIcon";
import { SVGIcon } from "@react-md/core/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function QrCodeTwoToneIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M5 15h4v4H5zM5 5h4v4H5zm10 0h4v4h-4z" opacity=".3" />
        <path d="M3 11h8V3H3zm2-6h4v4H5zM3 21h8v-8H3zm2-6h4v4H5zm8-12v8h8V3zm6 6h-4V5h4zm0 10h2v2h-2zm-6-6h2v2h-2zm2 2h2v2h-2zm-2 2h2v2h-2zm2 2h2v2h-2zm2-2h2v2h-2zm0-4h2v2h-2zm2 2h2v2h-2z" />
      </SVGIcon>
    );
  }
);
