// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { type SVGIconProps } from "@react-md/core/SVGIcon";
import { SVGIcon } from "@react-md/core/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function SignalCellularAlt1BarIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M5 14h3v6H5z" />
      </SVGIcon>
    );
  }
);
