// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { type SVGIconProps } from "@react-md/core/SVGIcon";
import { SVGIcon } from "@react-md/core/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function SnowingIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M6 12.75a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5M4.75 6a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0m12 8a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0m0-8a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0m-9 12a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0m0-8a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0m3 4a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0m0-8a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0m3 12a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0m0-8a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0" />
      </SVGIcon>
    );
  }
);
