// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { forwardRef } from "react";
import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";

export default forwardRef<SVGSVGElement, SVGIconProps>(
  function TornadoOutlinedIcon(props, ref) {
    return (
      <SVGIcon {...props} ref={ref}>
        <path d="M23 3H1l11 19zm-3.47 2-1.74 3H6.21L4.47 5zm-9.27 10h3.48L12 18.01zm4.64-2H9.1l-1.74-3h9.27z" />
      </SVGIcon>
    );
  }
);
