// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";
import { type ReactElement } from "react";

export default function VerticalShadesClosedRoundedIcon(
  props: SVGIconProps
): ReactElement {
  const { ref, ...remaining } = props;

  return (
    <SVGIcon {...remaining} ref={ref}>
      <path d="M20 19V5c0-1.1-.9-2-2-2H6c-1.1 0-2 .9-2 2v14H3c-.55 0-1 .45-1 1s.45 1 1 1h18c.55 0 1-.45 1-1s-.45-1-1-1zM13 5h1.5v14H13zm-2 14H9.5V5H11zM6 5h1.5v14H6zm10.5 14V5H18v14z" />
    </SVGIcon>
  );
}
