// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY

import { SVGIcon, type SVGIconProps } from "@react-md/core/icon/SVGIcon";
import { type ReactElement } from "react";

export default function ViewHeadlineRoundedIcon(
  props: SVGIconProps
): ReactElement {
  const { ref, ...remaining } = props;

  return (
    <SVGIcon {...remaining} ref={ref}>
      <path d="M5 15h14c.55 0 1-.45 1-1s-.45-1-1-1H5c-.55 0-1 .45-1 1s.45 1 1 1m0 4h14c.55 0 1-.45 1-1s-.45-1-1-1H5c-.55 0-1 .45-1 1s.45 1 1 1m0-8h14c.55 0 1-.45 1-1s-.45-1-1-1H5c-.55 0-1 .45-1 1s.45 1 1 1M4 6c0 .55.45 1 1 1h14c.55 0 1-.45 1-1s-.45-1-1-1H5c-.55 0-1 .45-1 1" />
    </SVGIcon>
  );
}
