# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Lint, and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, next, develop]

jobs:
  build_node_matrix:
    name: Build Using Node Matrix
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn
      - run: yarn setup
      - run: yarn dev-utils doc-index
      - run: yarn lint
      - run: yarn test

  build_node_14:
    # only want to use codecov for node 16
    name: Build Using Node 16
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn setup
      - run: yarn dev-utils doc-index
      - run: yarn lint
      - run: yarn test --coverage
      - run: npx codecov -t ${{ secrets.CODECOV_TOKEN }}
